#INCLUDE 'Rwmake.ch'
#INCLUDE 'Protheus.ch'
#INCLUDE 'Tbiconn.ch'
#INCLUDE 'Topconn.ch'
#Include 'totvs.ch'

/*/{Protheus.doc} LOSF0001
Funcao que processara os xmls
@type Function
@version 12.1.2410
@author Andre Vicente
@since 13/10/2025
@obs: 

/*/
User Function LOSF0001()
    Local aStart 
    Local lGridOk := .f. 
    
    Private oGrid

    aStart := {"01","01010001"}

    PREPARE ENVIRONMENT EMPRESA aStart[1] FILIAL aStart[2]


    oGrid := GridClient():New()
    cFnStart  	:= 'U_LOSF001E' //Função que prepara o ambiente no processamento GRID
    cFnExec  	:= 'U_LOSF001G' //Função que inclui as NFe no processamento GRID
    cFnFinal	:= 'U_LOSF001F' //Função executada no fim da grid

    lGridOk := oGrid:Prepare(cFnStart,aStart,cfnExec,cFnFinal) //Síncrono: comentar esse trecho todo para usar o processo síncrono

    If !lGridOk
        conout("---------------- Falha de Preparação do Grid --------------------------")
        conout(oGrid:GetError())
        oGrid:Terminate()
        oGrid := NIL
        Return
    Endif

    IF SELECT ("TMPZZ1") > 0
        TMPZZ1->( dbCloseArea( ) )
    ENDIF	
    
    BeginSql Alias  "TMPZZ1"

        SELECT 
               ZZ1.R_E_C_N_O_ AS RECZZ1,
               ZZ1.ZZ1_TIPO AS TIPO
          FROM %TABLE:ZZ1% ZZ1
         WHERE ZZ1.%NOTDEL%
           AND ZZ1.ZZ1_STATUS = 'A'
         ORDER BY R_E_C_N_O_
                
    EndSql

    DbSelectArea('TMPZZ1')
    TMPZZ1->(DbGoTop())
    
    While !TMPZZ1->(Eof()) 

        aParams := {TMPZZ1->TIPO, TMPZZ1->RECZZ1, "P"}

        lGridOk := oGrid:execute(aParams)

        TMPZZ1->( DbSkip() )
    EndDo
    TMPZZ1->( DbCloseArea() )

    If lGridOk
		lGridOk := oGrid:Terminate()
	Endif

    conout('------------------ FIM DO PROCESSAMENTO DA GRID LOSF0001 --------------------')
return 

/*/{Protheus.doc} LOSF001G
(long_description)
@type user function
@author user
@since 26/11/2025
@version version
@param param_name, param_type, param_descr
@return return_var, return_type, return_description
@example
(examples)
@see (links_or_references)
/*/
User Function LOSF001G(aParams)
    if aParams[1] == "1" //CTE
        cRet := LOSF001C(aParams[2], aParams[3])   
    elseif aParams[1] == "2" //NFse
        cRet := ProcesNFse(aParams[2], aParams[3])   
    endif
Return 

/*/{Protheus.doc} LOSF001E
(long_description)
@type user function
@author user
@since 26/11/2025
@version version
@param param_name, param_type, param_descr
@return return_var, return_type, return_description
@example
(examples)
@see (links_or_references)
/*/
User Function LOSF001E()
	PREPARE ENVIRONMENT EMPRESA aStart[1] FILIAL aStart[2]
	conout("Prepare environment => "+aStart[1] +' e '+ aStart[2] )
Return .T.

/*/{Protheus.doc} LOSF001F
  (long_description)
  @type  Static Function
  @author user
  @since 26/11/2025
  @version version
  @param param_name, param_type, param_descr
  @return return_var, return_type, return_description
  @example
  (examples)
  @see (links_or_references)
/*/
Static Function LOSF001F()
return

User Function LOSF001D(nRecNoZZ1, cStatus, cTipo)
    Local cRet
    Local   _cQuery   := ""
	Local   _cQCorpo := ""
    Private cErrorBlock := ''
    Private cYNumSer    := ''
    Private cYNumNF     := ''
    Default nRecNoZZ1 := 0
    Default cStatus := 'A'
    Default cTipo := '1'

    If Empty(FunName())
        PREPARE ENVIRONMENT EMPRESA '01' FILIAL '01010001'
        //PREPARE ENVIRONMENT EMPRESA '99' FILIAL '01'
    EndIf
    
    _cQuery := " AND ZZ1_STATUS = '" + cStatus + "' "
    
    if valtype(nRecNoZZ1) == "C"
        nRecNoZZ1 := val(nRecNoZZ1)
    endif

    If nRecNoZZ1 != 0
        _cQuery += " AND ZZ1.R_E_C_N_O_  = " + cValToChar(nRecNoZZ1)
    EndIf

//    _cQuery += " AND ZZ1.ZZ1_TIPO  = '" + cValToChar(cTipo) + "' "
//    _cQuery += " AND ZZ1.ZZ1_DATA = '20260102' "
//    _cQuery += " AND ZZ1.ZZ1_ACAO = 'I' "

    _cQCorpo := '%' + _cQuery  + '%'

    IF SELECT ("TMPZZ1") > 0
        TMPZZ1->( dbCloseArea( ) )
    ENDIF	
    
    BeginSql Alias  "TMPZZ1"

        %noparser%
        
        SELECT 
            ZZ1.R_E_C_N_O_ AS RECZZ1,
            ZZ1.ZZ1_TIPO AS TIPO
        FROM %TABLE:ZZ1% ZZ1
        WHERE ZZ1.%NOTDEL%
             %Exp:_cQCorpo%
        ORDER BY R_E_C_N_O_
                
    EndSql
    
    //MEMOWRITE("C:\TEMP\LOSF0001.sql",GETLASTQUERY()[2]) 	

    DbSelectArea('TMPZZ1')
    TMPZZ1->(DbGoTop())
    
    While !TMPZZ1->(Eof()) 

        if TMPZZ1->TIPO == "1" //CTE
            //cRet := ProcessaCTE('P')   
            cRet := LOSF001C(TMPZZ1->RECZZ1, 'P')   
        elseif TMPZZ1->TIPO == "2" //NFse
            cRet := ProcesNFse(TMPZZ1->RECZZ1, 'P')   
        endif

        TMPZZ1->(DbSkip())
    EndDo

Return cRet

/*/{Protheus.doc} LOSF001C
    Processa CTE de acordo com o tipo
    @type  Static Function
    @author Leonardo Freitas
    @since 10/11/2025
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Static Function LOSF001C(nRecno_, cTipo_)
    
    ZZ1->( dbSetOrder(1) )
    ZZ1->( dbGoTo(nRecno_) )

    Do Case
        Case Alltrim(ZZ1->ZZ1_ACAO) $ 'I,S' //Inclusao
            cRet := ProcessaCTE(cTipo_)   
        Case Alltrim(ZZ1->ZZ1_ACAO) == 'E' //Cancelamento
            cRet := ProcessaCTE(cTipo_)   
        Case Alltrim(ZZ1->ZZ1_ACAO) == 'C' //Complemento
            cRet := ProcessaCTE(cTipo_)   
        Otherwise
        
    EndCase
Return 



/*/{Protheus.doc} LOSF0001B
 *Usada no reprocessamento dos dados fiscais
/*/
User Function LOSF001B(cTipo)
    Local cTitulo := ''
    Default cTipo := ''

    If cTipo == 'P'
        cTitulo := "Processando nota"
    ElseIf cTipo == 'R'
        cTitulo := "Reprocessando dados fiscais"
    ElseIf cTipo == 'E'
        cTitulo := "Excluindo dados fiscais"
    Else
        cTipo := ""
    EndIf

    If !Empty(cTipo)
        if ZZ1->ZZ1_TIPO == "1" //CTE
            cRet := ProcessaCTE(cTipo )
        elseif ZZ1->ZZ1_TIPO == "2" //NFse
            cRet := ProcesNFse(ZZ1->(recno()), cTipo)
        endif
        //MSAguarde( { || ProcessaCTE(ZZ1->(Recno()), cTipo ) }, cTitulo ,"Processando...",.F.)
    EndIf
    
Return cRet

/*/{Protheus.doc} ProcesNFse
    (long_description)
    @type  Static Function
    @author user
    @since 24/10/2025
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Static Function ProcesNFse(nRecno_, cTipo_)

    Local oData := JsonObject():new()
    Local oIntNFse := IntegraNF():new()

    ZZ1->( dbSetOrder(1) )
    ZZ1->( dbGoTo(nRecno_) )

    oData:fromJson(ZZ1->ZZ1_JSON)

    lReturn_ := oIntNFse:integrar(oData)

Return 

/*/{Protheus.doc} incluiCTE
    (long_description)
    @type  Static Function
    @author user
    @since 10/11/2025
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
/*Static Function incluiCTE(cTipo_)

    //local i
    local oData := JsonObject():new()

    varError := ErrorClass():New()

    TRY 

        //Posiona o registro para processamento
        //ZZ1->(DbGoTo(nRecZZ1))
        cXml := ZZ1->ZZ1_XML
        
        //Valida o cadastro do tipo CTE no cadastro de tipos de titulos do financeiro
        If !  SX5->(DbSeek(xFilial('SX5') +  '05' + 'CTE'))
            varError:genCode := 001
            varError:description := "Tipo CTE nao localizado no cadastro de tipo de titulos"
            throw varError
        EndIf

        //Transforma o CTE em um objeto
        oCTE := xmlParser(cXML, "_", @cErro, @cAviso)    
            
        //Valida o objeto    
        If ValType(oCTE) == 'U'
            varError:genCode := 001
            varError:description := 'Erro no objeto XML: ' + cErro
            throw varError
        EndIf

        if ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_SERIE:TEXT","string")) != 'U'
            oData["serie"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_SERIE:TEXT","string")
        else 
            varError:genCode := 001
            varError:description := "Tag 'Serie CTE' nao encontrada no xml do CTE"
            throw varError
        endif
        
        if ValType( WSAdvValue( oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_NCT:TEXT","string" ) ) != 'U'
            oData["numero"] := PADL( WSAdvValue( oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_NCT:TEXT","string" ),TAMSX3("F2_DOC")[1],"0")
        else 
            varError:genCode := 001
            varError:description := "Tag 'Numero CTE' nao encontrada no xml do CTE"
            throw varError
        endif
        
        if ValType( WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EMIT:_CNPJ:TEXT","string") ) != 'U'
            oData["cnpjEmitente"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EMIT:_CNPJ:TEXT","string")
        else 
            varError:genCode := 001
            varError:description := "Tag 'CNPJ Emitente' nao encontrada no xml do CTE"
            throw varError
        endif

        if ValType( WSAdvValue(oCTE,"_CTEPROC:_PROTCTE:_INFPROT:_CHCTE:TEXT","string") ) != 'U'
            oData["chaveCte"] := WSAdvValue(oCTE,"_CTEPROC:_PROTCTE:_INFPROT:_CHCTE:TEXT","string")
        else 
            varError:genCode := 001
            varError:description := "Tag 'Chave CTE' nao encontrada no xml do CTE"
            throw varError
        endif

        if ValType( WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_CFOP:TEXT","string") ) != 'U'
            oData["cfop"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_CFOP:TEXT","string")
        else 
            varError:genCode := 001
            varError:description := "Tag 'CFOP' nao encontrada no xml do CTE"
            throw varError
        endif

        if ValType( WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_DHEMI:TEXT","string") ) != 'U'
            oData["emissao"] := StoD(StrTran(Left(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_DHEMI:TEXT","string"),10),'-',''))
        else 
            varError:genCode := 001
            varError:description := "Tag 'Emissao' nao encontrada no xml do CTE"
            throw varError
        endif

        if ValType( WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_VPREST:_VTPREST:TEXT","string") ) != 'U'
            oData["valorFrete"] := val( WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_VPREST:_VTPREST:TEXT","string") )
        else 
            varError:genCode := 001
            varError:description := "Tag 'Valor Frete' nao encontrada no xml do CTE"
            throw varError
        endif

        if ValType( WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_UFINI:TEXT","string") ) != 'U'
            oData["ufInicial"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_UFINI:TEXT","string")
        else 
            varError:genCode := 001
            varError:description := "Tag 'UF Inicial' nao encontrada no xml do CTE"
            throw varError
        endif

        if ValType( WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_UFFIM:TEXT","string") ) != 'U'
            oData["ufDestino"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_UFFIM:TEXT","string")
        else 
            varError:genCode := 001
            varError:description := "Tag 'UF Destino' nao encontrada no xml do CTE"
            throw varError
        endif

        if ValType( WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_xNome:TEXT","string") ) != 'U'
            oData["nomeRemetente"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_xNome:TEXT","string")
        else 
            varError:genCode := 001
            varError:description := "Tag 'Nome Remetente' nao encontrada no xml do CTE"
            throw varError
        endif

        if ValType( WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_xNome:TEXT","string") ) != 'U'
            oData["nomeDestinatario"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_xNome:TEXT","string")
        else 
            varError:genCode := 001
            varError:description := "Tag 'Nome Destinatario' nao encontrada no xml do CTE"
            throw varError
        endif
        
        If ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_CNPJ:TEXT","string")) != "U"
            oData["remetente"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_CNPJ:TEXT","string")
        ElseIf ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_CPF:TEXT","string")) != "U"
            oData["remetente"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_CPF:TEXT","string")
        ElseIf ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_CNPJ:TEXT","string")) != "U"
            oData["remetente"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_CNPJ:TEXT","string")
        ElseIf ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_CPF:TEXT","string")) != "U"
            oData["remetente"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_CPF:TEXT","string")
        Else
            varError:genCode := 001
            varError:description := "Tag _INFCTE:_REM ou _INFCTE:_EXPED nao encontrada no xml do CTE"
            throw varError
        EndIf
        
        
        If ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_CNPJ:TEXT","string")) != "U"
            oData["cnpjDestinatario"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_CNPJ:TEXT","string")
        ElseIf ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_CPF:TEXT","string")) != "U"
            oData["cnpjDestinatario"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_CPF:TEXT","string")
        ElseIf ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_CNPJ:TEXT","string")) != "U"
            oData["cnpjDestinatario"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_CNPJ:TEXT","string")
        ElseIf ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_CPF:TEXT","string")) != "U"
            oData["cnpjDestinatario"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_CPF:TEXT","string")
        Else
            varError:genCode := 001
            varError:description := "Tag _INFCTE:_DEST:_CNPJ nao encontrada no xml do CTE"
            throw varError
        EndIf


        If Type('oProcess') != 'U'        	
            oProcess:SetRegua2(4)	
            oProcess:IncRegua2("Validando XML...")		    
        EndIf

        If ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_TOMA3:_TOMA:TEXT","string")) != "U"
            oData["tomador"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_TOMA3:_TOMA:TEXT","string")
        ElseIf ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_TOMA4:_TOMA:TEXT","string")) != "U"
            oData["tomador"] := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_TOMA4:_TOMA:TEXT","string")
        Else
            varError:genCode := 001
            varError:description := "Tag 'Tomador' nao encontrada no xml do CTE"
            throw varError
        EndIf

        
        If Type('oProcess') != 'U'        	
            oProcess:IncRegua2("Processando CTE " +  cYNumNF + '/' + cYNumSer)
        EndIf





        //Alteracao da data base
        //dEmissao    := StoD(StrTran(Left(dEmissao,10),'-',''))
        //dDatabase   := dEmissao

        //Pega o valor total do frete
        //nVlrFrete   := Val(nVlrFrete)
        
        //dados dos vendedores, passa por parametro o array com os dados dos vendedores
        aXMLVend := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_COMPL:_OBSCONT","string")
        oData["vendedores"]   := dadosVend(aXMLVend, nVlrFrete)

        //Seta a filial que corresponde ao CNPJ
        If ! setEmpresa(odata["cnpjEmitente"])
            varError:genCode := 001
            varError:description := 'Cadastro de filial nao localizado com o CNPJ ' + cCNPJ
            throw varError
        EndIf

        //Posiciona o cliente    
        //cCNPJCli := getTomador(cTomador, oCTE)
        aTomador := getTomador(oData["tomador"], oCTE)

        If Empty(aTomador[1])
            varError:genCode := 001
            varError:description := 'Erro ao tentar obter o CNPJ do tomador.'
            throw varError
        EndIf

        //Posiciona o cliente pelo CNPJ do tomador
        SA1->(dbSetOrder(3))
        If SA1->(DbSeek( xFilial("SA1") + PADR(aTomador[1],TamSx3("A1_CGC")[1]) ))
            cCODCli := SA1->A1_COD
            cLojCli := SA1->A1_LOJA
            cNomCli := SA1->A1_NOME
            RecLock('ZZ1', .F.)
                ZZ1->ZZ1_FILCTE := cFilAnt
                ZZ1->ZZ1_CLIENT := SA1->A1_COD
                ZZ1->ZZ1_LOJA   := SA1->A1_LOJA
            ZZ1->(MsUnLock())
            _lok := .T.
        Else
            cMensagem :=  U_LOSF0004(&("oCTE:" + aTomador[2]),&("oCTE:" + aTomador[3]))

            if !empty(cMensagem)
                varError:genCode := 001
                varError:description := cMensagem
                throw varError
            else 
                _lok := .T.
            endif

            RecLock('ZZ1', .F.)
                ZZ1->ZZ1_CGC := aTomador[1]
                ZZ1->ZZ1_FILCTE := cFilAnt
                ZZ1->ZZ1_CLIENT := SA1->A1_COD
                ZZ1->ZZ1_LOJA   := SA1->A1_LOJA
            ZZ1->(MsUnLock())
        EndIf 

        
        
        oTomador := JsonObject():new()
        oTomador["cgc"] := ZZ1->ZZ1_CGC 
        oTomador["codigo"] := ZZ1->ZZ1_CLIENT 
        oTomador["loja"] := ZZ1->ZZ1_LOJA

        odata["tomador"] := oTomador

        //Verifica o remetente, se nao tiver, GRAVA NA SA1
        If _lok

            If AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_REM,"_CNPJ") 
                cCNPJRem :=  Upper(AllTrim(oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_CNPJ:Text))
            EndIf

            if empty(cCNPJRem)
                If AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_REM,"_CPF") 
                    cCNPJRem := Upper(AllTrim(oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_CPF:Text))
                EndIf
            endif
            

            SA1->(dbSetOrder(3))
            If SA1->(DbSeek( xFilial("SA1") + PADR(cCNPJRem,TamSx3("A1_CGC")[1]) ))
                cCODRem := SA1->A1_COD
                cLojRem := SA1->A1_LOJA
                cNomRem := SA1->A1_NOME
                _lok := .T.
            Else
                SA1->(dbSetOrder(3))
                cMensagem :=   U_LOSF0004(oCTE:_CTEPROC:_CTE:_INFCTE:_REM,oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_ENDERREME)

                if !empty(cMensagem)
                    varError:genCode := 001
                    varError:description := cMensagem
                    throw varError
                else
                    _lok := .T.
                endif
                If _lok
                    If SA1->(DbSeek( xFilial("SA1") + PADR(cCNPJRem,TamSx3("A1_CGC")[1]) ))
                        cCODRem := SA1->A1_COD
                        cLojRem := SA1->A1_LOJA
                        cNomRem := SA1->A1_NOME
                    Endif
                Endif    
            EndIf

            oRemetente := JsonObject():new()
            oRemetente["codigo"] := cCODRem 
            oRemetente["loja"] := cLojRem
            oRemetente["nome"] := cNomRem

            oData["remetente"] := oRemetente

        Endif

        cTes := getTes(cCFOP)
        
        If Empty(cTes)
            oError := ErrorClass():new()
            oError:genCode := 001
            oError:description := 'TES nao localizada para o CFOP ' + cCFOP
            THROW oError
        EndIf

        oData["tes"] := cTes

        //Verifica o destinatario, se nao tiver, nao usa        
        SA1->(dbSetOrder(3))
        If SA1->(DbSeek(xFilial('SA1') + cCnpjDest))
            cCODDes := SA1->A1_COD
            cLojDes := SA1->A1_LOJA
            cNomDes := SA1->A1_NOME
        
        Else
            cMensagem  :=   U_LOSF0004(oCTE:_CTEPROC:_CTE:_INFCTE:_DEST, oCTE:_CTEPROC:_CTE:_INFCTE:_DEST:_ENDERDEST)//GravaSA1(cCnpjDest,cNomDest)
            
            if !empty(cMensagem)
                varError:genCode := 001
                varError:description := cMensagem
                throw varError
            else 
                _lok := .T.
            endif
            
            If _lok 
                If SA1->(DbSeek(xFilial('SA1') + cCnpjDest))
                    cCODDes := SA1->A1_COD
                    cLojDes := SA1->A1_LOJA
                    cNomDes := SA1->A1_NOME
                Endif
            EndIf    
        
        EndIf

        

    CATCH oError 

        recLock( "ZZ1", .F. )
            ZZ1->ZZ1_STATUS := "E"
        ZZ1->( msUnlock() )

        CHKFILE("ZZ2")

        DBSelectArea( "ZZ2" )
        recLock("ZZ2", .T.)
            ZZ2->ZZ2_FILIAL := ZZ1->ZZ1_FILIAL 
            ZZ2->ZZ2_codigo := getSx8Num("ZZ2", "ZZ2_CODIGO")
            ZZ2->ZZ2_codzz1 := ZZ1->ZZ1_CODIGO
            ZZ2->ZZ2_status := "E"
            ZZ2->ZZ2_dtpros := dDataBase
            ZZ2->ZZ2_hrpros := time()
            ZZ2->ZZ2_log    := oError:description
        ZZ2->( msUnLock() )

    ENDTRY
Return */

/*/{Protheus.doc} ProcessaCTE
 * Funcao que faz o processamento dos CTEs incluindo os pedidos de venda
/*/
Static Function ProcessaCTE( cTipo )
    Local _lok        := .f.
    local i             := 0
    Private cAviso    := ''
    Private cErro     := ''
    Private cArqErro	:= "erroauto.txt"    
    Private cCond     := SuperGetMv("MS_CONDTRA",.F.,"000")
    Private cCNPJ, cCHVNFE, cTes, oCTE
    Private bBlock 	    := ErrorBlock()
    Private cMensagem 	:= ""
    Private cTpFrete 	:= ""
    Private aNFS 	    := {}
    Private aMinutas    := {}
    Private cChvOld := ""
    Private cTPSERV := ""
    Private cTPCTE := ""

    varError := ErrorClass():New()

    TRY 

        //Posiona o registro para processamento
//        ZZ1->(DbGoTo(nRecZZ1))
        cXml := ZZ1->ZZ1_XML
        cJson := ZZ1->ZZ1_JSON

        if !empty(cJson)
            oData := JsonObject():new()
            oData:fromJson(cJson) 

            if oData:hasProperty("minutas")
                aMinutas := oData["minutas"]
            endif
        endif
        
        //Valida o cadastro do tipo CTE no cadastro de tipos de titulos do financeiro
        If !  SX5->(DbSeek(xFilial('SX5') +  '05' + 'CTE'))
            varError:genCode := 001
            varError:description := "Tipo CTE nao localizado no cadastro de tipo de titulos"
            throw varError
        EndIf

        //Transforma o CTE em um objeto
        oCTE := xmlParser(cXML, "_", @cErro, @cAviso)    
            
        //Valida o objeto    
        If ValType(oCTE) == 'U'
            varError:genCode := 001
            varError:description := 'Erro no objeto XML: ' + cErro
            throw varError
        EndIf

        
        If cTipo == 'P' .AND. Alltrim(ZZ1->ZZ1_ACAO) == 'E' // Cancela nota
            CancelaCTE()
            
            if !empty(cMensagem)
                varError:genCode := 001
                varError:description := cMensagem
                throw varError
            endif

            return cMensagem
        endif 

/*        if cTipo == 'P' .AND. Alltrim(ZZ1->ZZ1_ACAO) == '2' // Cancela nota
            InutCTE()
            if !empty(cMensagem)
                varError:genCode := 001
                varError:description := cMensagem
                throw varError
            endif
        EndIf
*/        

        aVars := {}
        aAdd(aVars, {"Serie CTE"        , "cYNumSer"    , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_SERIE:TEXT","string")})
        aAdd(aVars, {"Numero CTE"       , "cYNumNF"     , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_NCT:TEXT","string")  })
        aAdd(aVars, {"CNPJ Emitente"    , "cCNPJ"       , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EMIT:_CNPJ:TEXT","string")})
        aAdd(aVars, {"Chave CTE"        , "cCHVNFE"     , WSAdvValue(oCTE,"_CTEPROC:_PROTCTE:_INFPROT:_CHCTE:TEXT","string")})
        aAdd(aVars, {"CFOP"             , "cCFOP"       , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_CFOP:TEXT","string")})
        aAdd(aVars, {"Emissao"          , "dEmissao"    , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_DHEMI:TEXT","string")})
        aAdd(aVars, {"Valor Frete"      , "nVlrFrete"   , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_VPREST:_VTPREST:TEXT","string")})
        aAdd(aVars, {"UF Inicial"       , "cUFORIG"     , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_UFINI:TEXT","string")})
        aAdd(aVars, {"Municipio Origem" , "cMunOrig"    , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_CMUNINI:TEXT","string")})
        aAdd(aVars, {"UF Destino"       , "cUFDEST"     , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_UFFIM:TEXT","string")})
        aAdd(aVars, {"Municipio Destino", "cMunDest"    , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_CMUNFIM:TEXT","string")})
        
        lRem := .F.
        if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE, "_REM")
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_REM, "_CNPJ")
                if !empty(oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_CNPJ:TEXT)
                    lRem := .T.
                endif
            endif
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_REM, "_CPF")
                if !empty(oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_CPF:TEXT)
                    lRem := .T.
                endif
            endif
        endif

        lAchouRem := .F.
        if lRem 
            If ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_CNPJ:TEXT","string")) != "U"
                if !empty(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_CNPJ:TEXT","string"))
                    aAdd(aVars, {"Remetente"     , "cCNPJRem"   , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_CNPJ:TEXT","string")})
                    aAdd(aVars, {"Nome Remetente"   , "cNomRem"     , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_xNome:TEXT","string")})
                    lAchouRem := .T.
                endif
            endif
            
            If ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_CPF:TEXT","string")) != "U"
                if !empty(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_CPF:TEXT","string"))
                    aAdd(aVars, {"Remetente"     , "cCNPJRem"   , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_CPF:TEXT","string")})
                    aAdd(aVars, {"Nome Remetente"   , "cNomRem"     , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_xNome:TEXT","string")})
                    lAchouRem := .T.
                endif
            endif
        else
            If ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_CNPJ:TEXT","string")) != "U"
                if !empty(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_CNPJ:TEXT","string"))
                    aAdd(aVars, {"Remetente"     , "cCNPJRem"   , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_CNPJ:TEXT","string")})
                    aAdd(aVars, {"Nome Remetente"   , "cNomRem"     , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_xNome:TEXT","string")})
                    lAchouRem := .T.
                endif
            endif
            If ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_CPF:TEXT","string")) != "U"
                if !empty(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_CPF:TEXT","string"))
                    aAdd(aVars, {"Remetente"     , "cCNPJRem"   , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_CPF:TEXT","string")})
                    aAdd(aVars, {"Nome Remetente"   , "cNomRem"     , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_EXPED:_xNome:TEXT","string")})
                    lAchouRem := .T.
                endif
            endif
        endif

        if !lAchouRem
            varError:genCode := 001
            varError:description := "Tag _INFCTE:_REM ou _INFCTE:_EXPED nao encontrada no xml do CTE"
            throw varError
        EndIf
        
        lDest := .F.
        if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE, "_DEST")
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_DEST, "_CNPJ")
                if !empty(oCTE:_CTEPROC:_CTE:_INFCTE:_DEST:_CNPJ:TEXT)
                    lDest := .T.
                endif
            else
                if !empty(oCTE:_CTEPROC:_CTE:_INFCTE:_DEST:_CPF:TEXT)
                    lDest := .T.
                endif
            endif
        endif

        lAchouDest := .F.
        If lDest
            If ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_CNPJ:TEXT","string")) != "U"
                if !empty(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_CNPJ:TEXT","string"))
                    aAdd(aVars, {"Destinatario"     , "cCnpjDest"   , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_CNPJ:TEXT","string")})
                    aAdd(aVars, {"Nome Dest"        , "cNomDest"    , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_xNome:TEXT","string")})
                    lAchouDest := .T.
                endif
            endif
            If ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_CPF:TEXT","string")) != "U"
                if !empty(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_CPF:TEXT","string"))
                    aAdd(aVars, {"Destinatario"     , "cCnpjDest"   , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_CPF:TEXT","string")})
                    aAdd(aVars, {"Nome Dest"        , "cNomDest"    , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_DEST:_xNome:TEXT","string")})
                    lAchouDest := .T.
                endif
            endif
        else 

            If ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_CNPJ:TEXT","string")) != "U"
                if !empty(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_CNPJ:TEXT","string"))
                    aAdd(aVars, {"Destinatario"     , "cCnpjDest"   , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_CNPJ:TEXT","string")})
                    aAdd(aVars, {"Nome Dest"        , "cNomDest"    , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_xNome:TEXT","string")})
                    lAchouDest := .T.
                endif
            endif
            If ValType(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_CPF:TEXT","string")) != "U"
                if !empty(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_CPF:TEXT","string"))
                    aAdd(aVars, {"Destinatario"     , "cCnpjDest"   , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_CPF:TEXT","string")})
                    aAdd(aVars, {"Nome Dest"        , "cNomDest"    , WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_RECEB:_xNome:TEXT","string")})
                    lAchouDest := .T.
                endif
            endif

        endif

        if !lAchouDest

            varError:genCode := 001
            varError:description := "Tag _INFCTE:_DEST ou _INFCTE:_RECEB nao encontrada no xml do CTE"
            throw varError

        EndIf

        

        If Type('oProcess') != 'U'        	
            oProcess:SetRegua2(4)	
            oProcess:IncRegua2("Validando XML...")		    
        EndIf

        //Valida se conseguiu recuperar as variaveis
        For i := 1 to Len(aVars)
            &(aVars[i][2]) := aVars[i][3]
            If ValType(&(aVars[i][2])) == 'U'
                varError:genCode := 001
                varError:description := "Tag " + aVars[i][1] + " nao encontrada no xml do CTE"
                throw varError
            EndIf
        Next

        nPIBSUF := 0
        nVIBSUF := 0
        nPIBSMUN := 0
        nVIBSMUN := 0
        nPCBS := 0
        nVCBS := 0
        if  AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP, "_IBSCBS")

            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_IBSCBS, "_GIBSCBS")
                
                //Pega o IBS Estadual
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_IBSCBS:_GIBSCBS, "_GIBSUF")
                    nPIBSUF := val(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_IBSCBS:_GIBSCBS:_GIBSUF:_PIBSUF:TEXT)
                    nVIBSUF := val(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_IBSCBS:_GIBSCBS:_GIBSUF:_VIBSUF:TEXT)
                endif

                //Pega o IBS Municipal
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_IBSCBS:_GIBSCBS, "_GIBSMUN")
                    nPIBSMUN := val(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_IBSCBS:_GIBSCBS:_GIBSMUN:_PIBSMUN:TEXT)
                    nVIBSMUN := val(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_IBSCBS:_GIBSCBS:_GIBSMUN:_VIBSMUN:TEXT)
                endif

                //Pega o CBS Federal
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_IBSCBS:_GIBSCBS, "_GCBS")
                    nPCBS := val(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_IBSCBS:_GIBSCBS:_GCBS:_PCBS:TEXT)
                    nVCBS := val(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_IBSCBS:_GIBSCBS:_GCBS:_VCBS:TEXT)
                endif

            endif
            cTPSERV := oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_TPSERV:TEXT
        endif

        nPesoBruto := 0
        nVolume1 := 0

        nValMerc  := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_VCARGA:TEXT","string")
        If ValType( nValMerc) != 'U'
            if valtype(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ) == "A"
                For i := 1 to Len(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ)
                    If Alltrim(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_TPMED:TEXT) == 'PESO BRUTO'        
                        //aAdd(aRet, {'FT_PESO'   , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_QCARGA:TEXT)})
                        nPesoBruto := Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_QCARGA:TEXT)

                    EndIf
                    If Alltrim(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_TPMED:TEXT) == "VOLUMES"
                        nVolume1 := Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_QCARGA:TEXT)
                    EndIf         
                Next
            else 
                nPesoBruto := Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ:_QCARGA:TEXT)
                nVolume1 := Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ:_QCARGA:TEXT)
            endif
        EndIf

        if  AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE, "_TPSERV")
            cTPSERV := oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_TPSERV:TEXT
        endif

        if  AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE, "_TPCTE")
            cTPCTE := alltrim(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_TPCTE:TEXT)
        endif
        
        //Caso for CTE Substituicao ira pegar a chavCTE anterior 
        if cTPCTE == "3"
            cChvOld := oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCTESUB:_CHCTE:TEXT
        endif

        cClasProd := getClasPro(ZZ1->ZZ1_CODPRO)

        if empty(cClasProd)
            varError:genCode := 001
            varError:description := "Classificacao do produto nao encontrado."
            throw varError 
        endif

        cCodProd := PADR(SuperGetMv('MS_PRODFRE',.F., 'FRETE          '), Len(SB1->B1_COD) )

/*
        //Caso for CTE de complemento irá pegar o produto do CTE anterior
        if cTPCTE == "1"
            if !AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTECOMP, "_CHCTE")
                varError:genCode := 001
                varError:description := "Tag _CHCTE referente ao CTE Normal nao encontrada no xml do CTE"
                throw varError
            endif
            
            cChvOld := oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTECOMP:_CHCTE:TEXT

            if empty(cChvOld)
                varError:genCode := 001
                varError:description := "CHAVE CTE ORIGINAL nao encontrada no xml do CTE"
                throw varError
            endif

            aProduto := getProdCte(cChvOld)

            if !aProduto[1]
                varError:genCode := 001
                varError:description := aProduto[2]
                throw varError
            endif

            cCodProd := aProduto[2]
        else 

            cDescProd := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_PROPRED:TEXT","string")
            cCodProd := POSICIONE( "SB1", 1, xFilial( "SB1" ) + cDescProd, "B1_COD" )

            if empty(cCodProd) 
                cCodProd := PADR(SuperGetMv('MS_PRODFRE',.F., 'FRETE          '), Len(SB1->B1_COD) )
                
                //varError:genCode := 001
                //varError:description := "Não foi possivel localizar o código do produto para este produto: " + cDescProd
                //throw varError
            endif

        endif
*/

        //Pega informações de ICMS
        cClasFis := ""
        nBaseIcms := 0
        nAliqIcms := 0
        nValIcms := 0

        if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS, "_ICMS00")
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00, "_CST")
                cClasFis := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_CST:TEXT","string")
            endif
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00, "_vBC")
                nBaseIcms := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_vBC:TEXT","string"))
            endif
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00, "_pICMS")
                nAliqIcms := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_pICMS:TEXT","string"))
            endif
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00, "_vICMS")
                nValIcms  := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_vICMS:TEXT","string"))
            endif
        endif

        if empty(cClasFis)
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS, "_ICMS45")
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS45, "_CST")
                    cClasFis := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS45:_CST:TEXT","string")
                endif
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS45, "_vBC")
                    nBaseIcms := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS45:_vBC:TEXT","string"))
                endif
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS45, "_pICMS")
                    nAliqIcms := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS45:_pICMS:TEXT","string"))
                endif
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS45, "_vICMS")
                    nValIcms  := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS45:_vICMS:TEXT","string"))
                endif
            endif
        endif

        if empty(cClasFis)
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS, "_ICMS60")
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS60, "_CST")
                    cClasFis := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS60:_CST:TEXT","string")
                endif
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS60, "_vBC")
                    nBaseIcms := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS60:_vBC:TEXT","string"))
                endif
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS60, "_pICMS")
                    nAliqIcms := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS60:_pICMS:TEXT","string"))
                endif
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS60, "_vICMS")
                    nValIcms  := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS60:_vICMS:TEXT","string"))
                endif
            endif
        endif

        if empty(cClasFis)
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS, "_ICMS90")
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS90, "_CST")
                    cClasFis := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS90:_CST:TEXT","string")
                endif
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS90, "_vBC")
                    nBaseIcms := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS90:_vBC:TEXT","string"))
                endif
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS90, "_pICMS")
                    nAliqIcms := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS90:_pICMS:TEXT","string"))
                endif
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS90, "_vICMS")
                    nValIcms  := val(WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS90:_vICMS:TEXT","string"))
                endif
            endif
        endif

        cTomador := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_TOMA3:_TOMA:TEXT","string")
        If ValType(cTomador) == 'U'
            cTomador := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IDE:_TOMA4:_TOMA:TEXT","string")
        EndIf

        If type('cTomador') == 'U'
            varError:genCode := 001
            varError:description := "Tag Tomador nao encontrada no xml do CTE"
            throw varError
        EndIf

        //Numero do CTE, preenche zeros a esquerda
        cYNumNF     := PADL(cYNumNF,TAMSX3("F2_DOC")[1],"0")
        
        If Type('oProcess') != 'U'        	
            oProcess:IncRegua2("Processando CTE " +  cYNumNF + '/' + cYNumSer)
        EndIf

        //Alteracao da data base
        dEmissao    := StoD(StrTran(Left(dEmissao,10),'-',''))
        dDatabase   := dEmissao

        //Pega o valor total do frete
        nVlrFrete   := Val(nVlrFrete)
        
        //dados dos vendedores, passa por parametro o array com os dados dos vendedores
        aXMLVend := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_COMPL:_OBSCONT","string")
        aVends   := dadosVend(aXMLVend, nVlrFrete)

        //Seta a filial que corresponde ao CNPJ
        If ! setEmpresa(cCNPJ)
            varError:genCode := 001
            varError:description := 'Cadastro de filial nao localizado com o CNPJ ' + cCNPJ
            throw varError
        EndIf

        //Posiciona o cliente    
        //cCNPJCli := getTomador(cTomador, oCTE)
        aTomador := getTomador(cTomador, oCTE)
        
        //Valida o CNPJ tomador
        /*If Empty(cCNPJCli)
            Return 'Erro ao tentar obter o CNPJ do tomador. 
        EndIf*/
        If Empty(aTomador[1])
            varError:genCode := 001
            varError:description := 'Erro ao tentar obter o CNPJ do tomador.'
            throw varError
        EndIf
/*
        //Posiciona o cliente pelo CNPJ do tomador
        SA1->(dbSetOrder(3))
        If SA1->(DbSeek( xFilial("SA1") + PADR(aTomador[1],TamSx3("A1_CGC")[1]) ))
            RecLock('ZZ1', .F.)
                ZZ1->ZZ1_FILCTE := cFilAnt
                ZZ1->ZZ1_CLIENT := SA1->A1_COD
                ZZ1->ZZ1_LOJA   := SA1->A1_LOJA
            ZZ1->(MsUnLock())
            cCODCli := SA1->A1_COD
            cLojCli := SA1->A1_LOJA
            cNomCli := SA1->A1_NOME
            _lok := .T.
        else 
            varError:genCode := 001
            varError:description := 'Cliente de CNPJ/CPF: ' + PADR(aTomador[1],TamSx3("A1_CGC")[1]) + ' não localizado!'
            throw varError
        endif
*/


        //Posiciona o cliente pelo CNPJ do tomador
        //SA1->(dbSetOrder(3))
        //If SA1->(DbSeek( xFilial("SA1") + PADR(aTomador[1],TamSx3("A1_CGC")[1]) ))
        aCliente := getCliente(cCNPJ := PADR(aTomador[1],TamSx3("A1_CGC")[1]), cIE := &("OCTE:" + aTomador[2] + ":_IE:TEXT"), cUF := &("OCTE:" + aTomador[3] + ":_UF:TEXT"))
        if aCliente[1] == .T.
            cCODCli := aCliente[2]//SA1->A1_COD
            cLojCli := aCliente[3]//SA1->A1_LOJA
            cNomCli := aCliente[4]//SA1->A1_NOME
            _lok := .T.
        Else
            RecLock('ZZ1', .F.)
                ZZ1->ZZ1_CGC := aTomador[1]
            ZZ1->(MsUnLock())
            cMensagem :=  U_LOSF0004(&("oCTE:" + aTomador[2]),&("oCTE:" + aTomador[3]))

            if !empty(cMensagem)
                varError:genCode := 001
                varError:description := cMensagem
                THROW varError
            else 
                lOk := .T.
            endif
        EndIf 
        
        //Verifico se existe cliente cadastrado antes de gravar
        //SA1->(dbSetOrder(3))
        If _lok
            //If SA1->(DbSeek( xFilial("SA1") + PADR(aTomador[1],TamSx3("A1_CGC")[1]) ))
            aCliente := getCliente(cCNPJ := PADR(aTomador[1],TamSx3("A1_CGC")[1]), cIE := &("OCTE:" + aTomador[2] + ":_IE:TEXT"), cUF := &("OCTE:" + aTomador[3] + ":_UF:TEXT"))
            if aCliente[1] == .T.
                RecLock('ZZ1', .F.)
                    ZZ1->ZZ1_FILCTE := cFilAnt
                    ZZ1->ZZ1_CLIENT := aCliente[2]//SA1->A1_COD
                    ZZ1->ZZ1_LOJA   := aCliente[3]//SA1->A1_LOJA
                ZZ1->(MsUnLock())
                cCODCli := aCliente[2]//SA1->A1_COD
                cLojCli := aCliente[3]//SA1->A1_LOJA
                cNomCli := aCliente[4]//SA1->A1_NOME
            Endif

        Endif

        //Verifica o remetente, se nao tiver, GRAVA NA SA1
        If _lok
/*
            lRem := .F.
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE, "_REM")
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_REM, "_CNPJ") .OR. AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_REM, "_CPF")
                    if !empty(oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_CNPJ:TEXT) .or. !empty(oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_CPF:TEXT)
                        lRem := .T.
                    endif
                endif
            endif
*/
            If lRem
                If AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_REM,"_CNPJ") 
                    if !empty(oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_CNPJ:Text)
                        cCNPJRem :=  Upper(AllTrim(oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_CNPJ:Text))
                    endif
                EndIf

                if empty(cCNPJRem)
                    If AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_REM,"_CPF") 
                        if !empty(oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_CPF:Text)
                            cCNPJRem := Upper(AllTrim(oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_CPF:Text))
                        endif
                    EndIf
                endif
            else 
                if empty(cCNPJRem)
                    If AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_EXPED,"_CNPJ") 
                        cCNPJRem := Upper(AllTrim(oCTE:_CTEPROC:_CTE:_INFCTE:_EXPED:_CNPJ:Text))
                    EndIf
                endif

                if empty(cCNPJRem)
                    If AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_EXPED,"_CPF") 
                        cCNPJRem := Upper(AllTrim(oCTE:_CTEPROC:_CTE:_INFCTE:_EXPED:_CPF:Text))
                    EndIf
                endif
            endif

            cIE := ""
            if lRem
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_REM,"_IE") 
                    cIE := oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_IE:TEXT
                    cUF := oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_ENDERREME:_UF:TEXT
                endif
            else 
                if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_EXPED,"_IE") 
                    cIE := oCTE:_CTEPROC:_CTE:_INFCTE:_EXPED:_IE:TEXT
                    cUF := oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_EXPED:_UF:TEXT
                endif
            endif
            
            aCliente := getCliente(cCNPJ := cCNPJRem, cIE := cIE, cUF := cUF)
            //SA1->(dbSetOrder(3))
            //If SA1->(DbSeek( xFilial("SA1") + PADR(cCNPJRem,TamSx3("A1_CGC")[1]) ))
            if aCliente[1] == .T.
                cCODRem := aCliente[2]//SA1->A1_COD
                cLojRem := aCliente[3]//SA1->A1_LOJA
                cNomRem := aCliente[4]//SA1->A1_NOME
                _lok := .T.
            Else
                //SA1->(dbSetOrder(3))
                
                if lRem
                    cMensagem :=   U_LOSF0004(oCTE:_CTEPROC:_CTE:_INFCTE:_REM,oCTE:_CTEPROC:_CTE:_INFCTE:_REM:_ENDERREME)
                else 
                    cMensagem :=   U_LOSF0004(oCTE:_CTEPROC:_CTE:_INFCTE:_EXPED,oCTE:_CTEPROC:_CTE:_INFCTE:_EXPED:_ENDEREXPED)
                endif

                if !empty(cMensagem)
                    oError := ErrorClass():new()
                    oError:genCode := 001
                    oError:description := cMensagem
                    THROW oError
                else 
                    lOk := .T.
                endif
                If _lok
                    //If SA1->(DbSeek( xFilial("SA1") + PADR(cCNPJRem,TamSx3("A1_CGC")[1]) ))
                    aCliente := getCliente(cCNPJ := cCNPJRem, cIE := cIE, cUF := cUF)
                    if aCliente[1] == .T.
                        cCODRem := aCliente[2]//SA1->A1_COD
                        cLojRem := aCliente[3]//SA1->A1_LOJA
                        cNomRem := aCliente[4]//SA1->A1_NOME
                    Endif
                Endif    
            EndIf   
        Endif
        //Verifica qual TES devera ser utilizada de acordo com o CFOP
        cTes := getTes(cCFOP, cClasFis)
        //cCst := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS45:_CST:TEXT","string")
        //If ValType(cCst) != "U"
        //    cTes := AllTrim(SuperGetMv("MS_TES45", .F., "53J"))
        //EndIf
        
        If Empty(cTes)
            gerError('TES nao localizada para o CFOP ' + cCFOP)
            return 'TES nao localizada para o CFOP ' + cCFOP
        EndIf
/*
        lDest := .F.
        if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE, "_DEST")
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_DEST, "_CNPJ") .OR. AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_DEST, "_CPF")
                if !empty(oCTE:_CTEPROC:_CTE:_INFCTE:_DEST:_CNPJ:TEXT) .or. !empty(oCTE:_CTEPROC:_CTE:_INFCTE:_DEST:_CPF:TEXT)
                    lDest := .T.
                endif
            endif
        endif
*/
        cIE := ""
        if lDest
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_DEST,"_IE") 
                cIE := oCTE:_CTEPROC:_CTE:_INFCTE:_DEST:_IE:TEXT
                cUF := oCTE:_CTEPROC:_CTE:_INFCTE:_DEST:_ENDERDEST:_UF:TEXT
            endif
        else 
            if AttIsMemberOf(oCTE:_CTEPROC:_CTE:_INFCTE:_RECEB,"_IE") 
                cIE := oCTE:_CTEPROC:_CTE:_INFCTE:_RECEB:_IE:TEXT
                cUF := oCTE:_CTEPROC:_CTE:_INFCTE:_DEST:_ENDERRECEB_UF:TEXT
            endif
        endif

        //Verifica o destinatario, se nao tiver, nao usa        
        //SA1->(dbSetOrder(3))
        //If SA1->(DbSeek(xFilial('SA1') + cCnpjDest))
        aCliente := getCliente(cCNPJ := cCnpjDest, cIE := cIE, cUF := cUF)
        if aCliente[1] == .T.
            cCODDes := aCliente[2]//SA1->A1_COD
            cLojDes := aCliente[3]//SA1->A1_LOJA
            cNomDes := aCliente[4]//SA1->A1_NOME
        Else

            if lDest
                cMensagem :=   U_LOSF0004(oCTE:_CTEPROC:_CTE:_INFCTE:_DEST, oCTE:_CTEPROC:_CTE:_INFCTE:_DEST:_ENDERDEST)//GravaSA1(cCnpjDest,cNomDest)
            else 
                cMensagem :=   U_LOSF0004(oCTE:_CTEPROC:_CTE:_INFCTE:_RECEB, oCTE:_CTEPROC:_CTE:_INFCTE:_RECEB:_ENDERRECEB)//GravaSA1(cCnpjDest,cNomDest)
            endif
            
            if !empty(cMensagem)
                oError := ErrorClass():new()
                oError:genCode := 001
                oError:description := cMensagem
                THROW oError
            else 
                lOk := .T.
            endif
            

            If _lok 
                //If SA1->(DbSeek(xFilial('SA1') + cCnpjDest))
                aCliente := getCliente(cCNPJ := cCnpjDest, cIE := cIE, cUF := cUF)
                if aCliente[1] == .T.
                    cCODDes := aCliente[2]//SA1->A1_COD
                    cLojDes := aCliente[3]//SA1->A1_LOJA
                    cNomDes := aCliente[4]//SA1->A1_NOME
                Endif
            EndIf    
        
        EndIf
        
        aNFS := getNfs(oCTE)
        
        /*
        If (cCODRem+ cLojRem) == (cCODCli + cLojCli)
            cTpFrete := "C"
        Else
            cTpFrete := "F"
        EndIf
        */

        Do Case
        Case cTomador $ "0,1"
            cTpFrete := "C"
        Case cTomador $ "2,3"
            cTpFrete := "F"
        Case cTomador $ "4"
            cTpFrete := "D"
        Otherwise
            oError := ErrorClass():new()
            oError:genCode := 001
            oError:description := 'Tipo de frete nao cadastrado para o tomador: ' + cTomador
            THROW oError
        EndCase

        cQuery := " SELECT R_E_C_N_O_ AS RECNO FROM "  + RetSqlName('SF2') + " SF2"
        cQuery += " WHERE SF2.D_E_L_E_T_ <> '*' AND F2_CHVNFE = '"+ZZ1->ZZ1_CHAVE+"' "
        
        If Select('QRY') > 0
            QRY->(dbclosearea())
        EndIf
        
        TcQuery cQuery New Alias 'QRY'

        If cTipo == 'P' .AND. Alltrim(ZZ1->ZZ1_ACAO) $ 'I,S' // Inclui|Processa a nota

            validSerie(cYNumSer)

            ProcCte(aVends)

            //Caso seja concluído com sucesso o retorno será vazio
            if empty(cMensagem)
                ZZ2->( dbSetOrder(1) )
                recLock("ZZ2", .T.)
                    ZZ2->ZZ2_FILIAL := ZZ1->ZZ1_FILIAL 
                    ZZ2->ZZ2_codigo := getSx8Num("ZZ2", "ZZ2_CODIGO")
                    ZZ2->ZZ2_codzz1 := ZZ1->ZZ1_CODIGO
                    ZZ2->ZZ2_status := "P"
                    ZZ2->ZZ2_dtpros := dDataBase
                    ZZ2->ZZ2_hrpros := time()
                    ZZ2->ZZ2_log    := "Integração processada com sucesso"
                ZZ2->( msUnLock() )
            else
                varError:genCode := 001
                varError:description := cMensagem
                throw varError
            endif
        //ElseIf cTipo == 'P' .AND. Alltrim(ZZ1->ZZ1_ACAO) == 'E' // Cancela nota
        //  CancelaCTE()
        ElseIf cTipo == 'P' .AND. Alltrim(ZZ1->ZZ1_ACAO) == 'U'// Inutiliza nota
            InutCTE()
        ElseIf cTipo == 'R'
            If QRY->(!EoF())
                cMensagem := ProcFis(.T., QRY->RECNO) //Reprocessa dados fiscais
                if !empty(cMensagem)
                    varError:genCode := 001
                    varError:description := cMensagem
                    throw varError
                endif
            EndIf
        ElseIf cTipo == 'E'
            If QRY->(!EoF())
                cMensagem := ProcFis(.F., QRY->RECNO) // Exclui dados fiscais
                if !empty(cMensagem)
                    varError:genCode := 001
                    varError:description := cMensagem
                    throw varError
                endif
            EndIf
        EndIf

    CATCH oError 

        recLock( "ZZ1", .F. )
            ZZ1->ZZ1_STATUS := "E"
        ZZ1->( msUnlock() )

        CHKFILE("ZZ2")

        DBSelectArea( "ZZ2" )
        recLock("ZZ2", .T.)
            ZZ2->ZZ2_FILIAL := ZZ1->ZZ1_FILIAL 
            ZZ2->ZZ2_codigo := getSx8Num("ZZ2", "ZZ2_CODIGO")
            ZZ2->ZZ2_codzz1 := ZZ1->ZZ1_CODIGO
            ZZ2->ZZ2_status := "E"
            ZZ2->ZZ2_dtpros := dDataBase
            ZZ2->ZZ2_hrpros := time()
            ZZ2->ZZ2_log    := iif(valtype(oError:description) == "U" ,"Erro desconhecido", oError:description)
        ZZ2->( msUnLock() )

    ENDTRY
    
    
    
Return cMensagem

/*/{Protheus.doc} validSerie
    (long_description)
    @type  Static Function
    @author user
    @since 06/11/2025
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Static Function validSerie(cYNumSer)
    
    SD9->( dbSetOrder( 1 ) )
    if !SD9->( dbSeek( cFilAnt + cYNumSer ) )
        recLock("SD9", .T.)
            SD9->D9_FILIAL := cFilAnt
            SD9->D9_SERIE := cYNumSer
            SD9->D9_DOC := PADL("1",TAMSX3("F2_DOC")[1],"0")
        SD9->( msUnlock() )
    endif

    SX5->( dbSetOrder( 1 ) )
    if !SX5->( dbSeek( xFilial( "SX5" ) + "SN" + PADR(cYNUMSER,TAMSX3("F2_SERIE")[1]," ") ) )
        recLock("SX5", .T.)
            SX5->X5_FILIAL := xFilial( "SX5" )
            SX5->X5_TABELA := "SN"
            SX5->X5_CHAVE := cYNumSer
            SX5->X5_DESCRI := cYNumSer + '=CTE'
            SX5->X5_DESCSPA := cYNumSer + '=CTE'
            SX5->X5_DESCENG := cYNumSer + '=CTE'
        SX5->( msUnLock() )
    endif

Return 


/*/{Protheus.doc} getTes
 * Funcao que retorna a tes de acordo com o CFOP
/*/
Static Function getTes(cCFOP, cClasFis_)
    Local cRet := ''

    cCFOP := SUBSTR(cCFOP,2,3)

    cQuery := " SELECT F4_CODIGO FROM " + RetSqlTab('SF4')
    cQuery += " WHERE D_E_L_E_T_ = ' '"
    cQuery += " AND SUBSTR(F4_CF,2,3) = '" + cCFOP + "' "
    cQuery += " AND F4_TIPO    = 'S'"  //TES DE SAIDA
    cQuery += " AND F4_DUPLIC  = 'S' " //TEM QUE GERAR DUPLICATA
    cQuery += " AND F4_ESTOQUE = 'N'"  //NAO PODE MOVIMENTAR ESTOQUE
//    if alltrim(cClasFis_) $ '40,41,60'
        cQuery += " AND F4_SITTRIB = '" + alltrim(cClasFis_) + "' "
//    endif

    If Select('QRYTES') > 0
        QRYTES->(DbCloseArea())
    EndIf

    TcQuery cQuery New Alias 'QRYTES'

    If QRYTES->(!Eof())
        cRet := QRYTES->F4_CODIGO
    EndIf

Return cRet


/*/{Protheus.doc} ProcFis
 * Metodo usado para exclusao e reprocessamento de dados fiscais da nota.
/*/
Static Function ProcFis(lReprocessa,nRecnoSF2)
    Local aRet := {}
    Local i, j
    Private nOrdem := 0
    Private cChave := ""
    Private aTabs := {}
    Private cAlias
    Private cCAMPO := ""
    Default nRecnoSF2 := 0
    Default lReprocessa := .F.


    SF2->(DbGoTo(nRecnoSF2))
    If SF2->(!EoF())
        //Posiona o registro para processamento
        cXml := ZZ1->ZZ1_XML

        //Transforma o CTE em um objeto
        oCTE := xmlParser(cXml, "_", @cErro, @cAviso)    
        cCNPJ := oCTE:_CTEPROC:_CTE:_INFCTE:_EMIT:_CNPJ:TEXT
        
        If ! setEmpresa(cCNPJ)
            return 'Cadastro de filial nao localizado com o CNPJ ' + cCNPJ
        EndIf

        //SA1->(DbSetOrder(1))
        //If SA1->(DbSeek(xFilial("SA1") + SF2->F2_CLIENTE + SF2->F2_LOJA))
        //EndIf
        //funcao que valida os erros em tempo de execucao
        ErrorBlock( {|e| cErrorBlock := e:Description + e:ErrorStack })
        BEGIN SEQUENCE
            aTabs := {}
                
            aAdd(aTabs, {'SF2', 1, SF2->(F2_FILIAL + F2_DOC + F2_SERIE + F2_CLIENTE + F2_LOJA), "SF2->(F2_FILIAL + F2_DOC + F2_SERIE + F2_CLIENTE + F2_LOJA)" })
            aAdd(aTabs, {'SD2', 3, SF2->(F2_FILIAL + F2_DOC + F2_SERIE + F2_CLIENTE + F2_LOJA), "SD2->(D2_FILIAL + D2_DOC + D2_SERIE + D2_CLIENTE + D2_LOJA)" })
            aAdd(aTabs, {'SF3', 4, SF2->(F2_FILIAL + F2_CLIENTE + F2_LOJA + F2_DOC + F2_SERIE), "SF3->(F3_FILIAL + F3_CLIEFOR + F3_LOJA + F3_NFISCAL + F3_SERIE)" }) 
            aAdd(aTabs, {'SFT', 1, SF2->F2_FILIAL + 'S' + SF2->(F2_SERIE + F2_DOC + F2_CLIENTE + F2_LOJA), "SFT->(FT_FILIAL + FT_TIPOMOV + FT_SERIE + FT_NFISCAL + FT_CLIEFOR + FT_LOJA)" })
            
            //Percorre o array de tabelas, preenchendo os campos extras
            For i := 1  to Len(aTabs)
                cAlias  := aTabs[i][1]
                nOrdem  := aTabs[i][2]
                cChave  := aTabs[i][3]
                
                //Retorna os dados que devem ser preenchidos na tabela
                aRet    := getArray(oCTE, cAlias, nRecnoSF2)          
                (cAlias)->(DbSetOrder(nOrdem))
                (cAlias)->(DbSeek(cChave))            
                
                //Perccorre os registro, na pratica, sempre sera um, porem, ja coloquei para evitar. 
                While (cAlias)->(!Eof()) .AND. cChave == &(aTabs[i][4])
                        //Altera os campos
                        RecLock(cAlias, .F.)
                            For j := 1 to Len(aRet)
                                cCampo := aRet[j][1]
                                xValor := aRet[j][2]
                                If Alltrim(cCampo) != "F2_CHVNFE"
                                    xValor := aRet[j][2]
                                    (cAlias)->&(cCampo) := Iif(!lReprocessa, GetVazio(cAlias,cCampo), xValor ) 
                                ElseIf lReprocessa 
                                    (cAlias)->&(cCampo) := xValor
                                EndIf
                            Next
                        (cAlias)->(MsUnLock())
                    
                    (cAlias)->(DbSkip())
                EndDo
            Next
            SF2->(DbGoTo(nRecnoSF2))
            If lReprocessa .AND. Alltrim(ZZ1->ZZ1_ACAO) $ 'I,S'
                //Cria o DT6, tabela do TMS, usada apenas para funcionar o registro fiscal
                aDT6 := getArray(oCTE, 'DT6', nRecnoSF2)
                DT6->(DBOrderNickname("DT6CHVCTE"))
                If !DT6->(DbSeek(xFilial("DT6") + ZZ1->ZZ1_CHAVE))
                    RecLock('DT6', .T.)            
                        For j := 1 to Len(aDT6)
                            cCampo := aDT6[j][1]
                            xValor := aDT6[j][2]
                            DT6->&(cCampo) := xValor
                        Next
                    DT6->(MsUnLock())
                EndIf

                RecLock('ZZ1', .F.)
                    //ZZ1->ZZ1_STATUS := 'P'
                    ZZ1->ZZ1_STAFIS := 'P'
                ZZ1->(MsUnLock())

                /*    
                For nZ := 1 To len(aNFS)
                    If !ZA8->(DbSeek(xFilial("ZA8") + ZZ1->ZZ1_CHAVE + PADR(aNFS[nZ],Len(ZZ1->ZZ1_CHAVE)) ))
                        RecLock('ZA8', .T.)
                            ZA8->ZA8_CHVCTE := ZZ1->ZZ1_CHAVE
                            ZA8->ZA8_CHVNFE := aNFS[nZ]
                        ZA8->(MsUnLock())
                    EndIf
                Next
                */
            Else
                //Exclui DT6
                DT6->(DBOrderNickname("DT6CHVCTE"))
                If DT6->(DbSeek(xFilial("DT6") + SF2->F2_CHVNFE))
                    RecLock('DT6', .F.)
                        DT6->(DbDelete())
                    DT6->(MsUnLock())
                    RecLock('ZZ1', .F.)
                        ZZ1->ZZ1_STATUS := 'P'
                        ZZ1->ZZ1_STAFIS := 'A'
                    ZZ1->(MsUnLock())
                EndIf
                /*
                For nZ := 1 To len(aNFS)
                    If ZA8->(DbSeek(xFilial("ZA8") + ZZ1->ZZ1_CHAVE + PADR(aNFS[nZ],Len(ZZ1->ZZ1_CHAVE)) ))
                        RecLock('ZA8', .F.)
                            ZA8->(DbDelete())
                        ZA8->(MsUnLock())
                    EndIf
                Next
                */
                
            EndIf
            RECOVER
        END SEQUENCE 
    EndIf
	
Return ""


/*/{Protheus.doc} GetVazio
 * Retorna valor vazio de acordo com tipo
/*/
Static Function GetVazio(cTab,cCampo)
    Local xRet := (cTab)->&(cCampo)

    If ValType(xRet) == 'N'
        xRet := 0
    ElseIf ValType(xRet) == 'L'
        xRet := .F.
    ElseIf ValType(xRet) == 'C'
        xRet := ""
    ElseIf ValType(xRet) == 'M'
        xRet := ""
    ElseIf ValType(xRet) == 'D'
        xRet := CtoD("")
    EndIf

Return xRet


/*/{Protheus.doc} ProcCte
 * Funcao que faz o processamento dos CTEs incluindo os pedidos de venda
/*/
Static Function ProcCte(aVends)
    Local oPedido	:=	TNYXPEDIDOS():New() //Classe da Newib agisrn
    Local i
    Local nDiasVenc := SuperGetMv("MS_DVENCT", .F., 365)
    Local _cNatureza := Alltrim(SuperGetMv("MS_NATCTE",.F.,"110101"))
    nDiasVenc := IIF( ValType(nDiasVenc) == 'C', Val(Alltrim(nDiasVenc)),nDiasVenc  )
   
    oPedido:lMostrarErro := .F.

    //Prepapara as propriedades do objeto pedidos
	oPedido:SERIENF	        := cYNumSer                       //SERIE DA NOTA
	oPedido:TIPONF		    := 'N'						    //TIPO DA NOTA
	oPedido:FORMULNF	    := Space(len(SF2->F2_FORMUL))	//FORMULARIO PROPRIO	
    oPedido:aC6CUSTOMFIELDS := {}
    oPedido:aC5CUSTOMFIELDS := {}
    oPedido:aC5toF2			:= {}
    oPedido:lCRIASB2		:= .F.
    oPedido:cTIPOTIT		:= 'CTE'

    //Numero que sera usado para o CTE
    aAdd(oPedido:aNUMNFS, cYNumNF )
    
    oCrud := crud():new('SC5', nil, 1)	
    
    //Posiciona o cliente final
    SA1->(DbSetOrder(1))
    SA1->(DbSeek(xFilial('SA1') + cCODCli + cLojCli))

	oCrud:Set('C5_TIPO'		, 'N'	        )
	oCrud:Set('C5_EMISSAO'	, dDatabase     )	
	oCrud:Set('C5_CLIENTE'	, SA1->A1_COD	)
	oCrud:Set('C5_LOJACLI'	, SA1->A1_LOJA	)
	oCrud:Set('C5_TIPOCLI'	, SA1->A1_TIPO	)
	oCrud:Set('C5_CONDPAG'	, cCond         ) 	//CONDICAO DE PGTO
	oCrud:Set('C5_UFDEST'	, cUFDEST       ) 	
	oCrud:Set('C5_CMUNDE'	, RIGHT(cMunDest, 5)       ) 	
	oCrud:Set('C5_UFORIG'	, cUFORIG       ) 	
	oCrud:Set('C5_CMUNOR'	, RIGHT(cMunOrig, 5)       ) 	
	oCrud:Set('C5_TPFRETE'	, cTpFrete      ) 	
	oCrud:Set('C5_NATUREZ'	, _cNatureza      ) 	

	oCrud:Set('C5_CLASFIS'	, cClasFis      ) 	

    //Cliente Remetente
	oCrud:Set('C5_CLIRET'	, cCODRem      ) 	
	oCrud:Set('C5_LOJARET'	, cLojRem      ) 	

    //Cliente Destino
	oCrud:Set('C5_CLIENT'	, cCODDes      ) 	
	oCrud:Set('C5_LOJAENT'	, cLojDes      ) 	

    //Peso/carga
	oCrud:Set('C5_PBRUTO'	, nPesoBruto      ) 	
	oCrud:Set('C5_VOLUME1'	, nVolume1      ) 	

    For i := 1 to Len(aVends)
        if aVends[i][4] != nil
            oCrud:Set('C5_VEND'  + cValToChar(i)	, aVends[i][4])
            oCrud:Set('C5_COMIS' + cValToChar(i)	, aVends[i][3])
            aAdd(oPedido:aC5CUSTOMFIELDS, 'C5_VEND' + cValToChar(i))
            aAdd(oPedido:aC5CUSTOMFIELDS, 'C5_COMIS' + cValToChar(i))
        endif
    Next

    oCrud:addChild('SC6')	
    
    cItem := '00'
    
    oCrud:addLine("SC6")

    cItem       := Soma1(cItem)
    //cProduto    := PADR(SuperGetMv('MS_PRODFRE',.F., 'FRETE          '), Len(SB1->B1_COD) )
    oCrud:set('C6_PRODUTO'	, cCodProd)
    oCrud:set('C6_ITEM'		, cItem)
    oCrud:set('C6_QTDVEN'	, 1)
    oCrud:set('C6_QTDLIB'	, 1)
    oCrud:set('C6_PRCVEN'	, nVlrFrete)
    oCrud:set('C6_PRUNIT'	, nVlrFrete)
    oCrud:set('C6_TES'		, cTes) 
    oCrud:set('C6_CONTA'	, GetConta()) 

    //oCrud:set('C6_CLASFIS'	, GetConta()) 
    oCrud:set('C6_CF'	    , cCFOP) 

    aAdd(oPedido:SC5, oCrud) 

    If Type('oProcess') != 'U'        	
        oProcess:IncRegua2("Gerando NF " +  cYNumNF + '/' + cYNumSer)
	EndIf
    If SX5->(DbSeek(cFilAnt + "01"+PADR("2",LEN(SX5->X5_CHAVE))))
        RecLock('SX5', .F.)
            SX5->X5_DESCRI := cYNumNF
        SX5->(MsUnLock())
    EndIf
    
    If ! oPedido:INCLUIRNF()
        MostraErro(GetSrvProfString("Startpath","") , cArqErro )
        cMensagem := Alltrim(MemoRead( GetSrvProfString("Startpath","") + '\' + cArqErro ))
    Else    

        If Type('oProcess') != 'U'        	
            oProcess:IncRegua2("Atualizando dados fiscais " +  cYNumNF + '/' + cYNumSer)
        EndIf

        //Caso for CTE Substituicao ira excluir o financeiro do CTE anterior
        if cTPCTE == "3"
            //cChvOld
            cMensagem := deleteSe1()

            if !empty(cMensagem)
                return cMensagem
            endif
        endif

        //Retorno para a rotina
        cMensagem := ''
        nRecNoSF2 := oPedido:DOCS[1]:nRecNo

        SF2->(dbSetOrder(1))
        SF2->(dbgoto(nRecNoSF2))
        RecLock("SF2", .F.)
            SF2->F2_CLASPRO := cClasProd
            SF2->F2_TPCTEGW := cTPCTE
            SF2->F2_TPSERGW := cTPSERV
            SF2->F2_CHAVOLD := cChvOld
            SF2->F2_PIBSUF  := nPIBSUF
            SF2->F2_VIBSUF  := nVIBSUF
            SF2->F2_PIBSMUN := nPIBSMUN
            SF2->F2_VIBSMUN := nVIBSMUN
            SF2->F2_PCBS    := nPCBS
            SF2->F2_VCBS    := nVCBS
        SF2->( msUnLock() )
        
        procMinutas(SF2->F2_FILIAL + SF2->F2_DOC + SF2->F2_SERIE + SF2->F2_CLIENTE + SF2->F2_LOJA + SF2->F2_FORMUL + SF2->F2_TIPO)

        RecLock('SE1', .F.)
            SE1->E1_PREFIXO  := cYNumSer
            SE1->E1_VENCTO  := dDataBase + nDiasVenc
            SE1->E1_VENCREA := dDataBase + nDiasVenc
            //SE1->E1_YTPFRET := cTpFrete
        SE1->(MsUnLock())

        RecLock('SC5', .F.)
            SC5->C5_TPFRETE := cTpFrete
        SC5->(MsUnLock())

        //Atualiza campos da tabela de integração 
        recLock("ZZ1", .F.)
            ZZ1->ZZ1_STATUS := 'P'
            ZZ1->ZZ1_NUMCTE := cYNumNF
            ZZ1->ZZ1_SERCTE := cYNumSer
        ZZ1->(MsUnLock())


        //Posiciona o SF2 para montar os dados que serao usados para as tabelas
        // SF2->(DbGoTo(nRecNoSF2))        
        ProcFis(.T.,nRecNoSF2)    
    EndIf

Return cMensagem

/*/{Protheus.doc} procMinutas
    (long_description)
    @type  Static Function
    @author user
    @since 30/12/2025
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Static Function procMinutas(cChvSF2)
    local i := 0

    for i := 1 to len(aMinutas)
        recLock("ZZ4", .T.)
            ZZ4->ZZ4_FILIAL := xFilial("ZZ4")
            ZZ4->ZZ4_CODSF2 := cChvSF2
            ZZ4->ZZ4_CHVNF   := aMinutas[i]["chave"]
        ZZ4->( msUnLock() )
    next
Return 

/*/{Protheus.doc} deleteSe1
    (long_description)
    @type  Static Function
    @author user
    @since 19/11/2025
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Static Function deleteSe1()

    Local aArea     := FWGetArea()

    SF2->(DBOrderNickname("IDXCHVNF"))
    if SF2->( dbSeek( xFilial("SF2") + cChvOld ) )
        SE1->( dbSetOrder(1) )
        if SE1->( dbSeek( cSeek_ := SF2->F2_FILIAL + SF2->F2_SERIE + SF2->F2_DOC ) )
            while SE1->( !EOF() ) .AND. SE1->E1_FILIAL + SE1->E1_PREFIXO + SE1->E1_NUM == cSeek_

                //Caso tiver sofrido baixa, estorna a baixa
                if !empty(SE1->E1_BAIXA)
                    cMensagem := estornaBxa()   
                endif

                if !empty(cMensagem)
                    return cMensagem
                endif

                recLock("SE1", .F.)
                    SE1->(dbDelete())
                SE1->( msUnLock() )

                SE1->( dbSkip() )
            endDo
        else 
            return "Nao foi possível localizar o contas a pagar referente ao CTE original"
        endif
    else 
        return "Nao foi possível localizar o CTE original"
    endif

    FWRestArea(aArea)
Return ""

/*/{Protheus.doc} estornaBxa
    (long_description)
    @type  Static Function
    @author user
    @since 24/11/2025
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Static Function estornaBxa()
    Local aBaixa := {}
     
    aBaixa := {{"E1_PREFIXO"  , SE1->E1_PREFIXO               ,Nil    },;
            {"E1_NUM"      , SE1->E1_NUM            ,Nil    },;
            {"E1_PARCELA"  , SE1->E1_PARCELA                    ,Nil    },;
            {"E1_TIPO"     , SE1->E1_TIPO                  ,Nil    },;
            {"AUTMOTBX"    , "CANCE"                 ,Nil    },;
            {"AUTDTBAIXA"  ,dDataBase              ,Nil    },;
            {"AUTDTCREDITO",dDataBase              ,Nil    },;
            {"AUTHIST"     ,"CANCELAMENTO DE BX"          ,Nil    },;
            {"AUTVALREC"   , SE1->E1_VALOR                    ,Nil    }}
  
    MSExecAuto({|x,y| Fina070(x,y)},aBaixa,5)

    If lMsErroAuto
        MostraErro(GetSrvProfString("Startpath","") , cArqErro )
        cMensagem := Alltrim(MemoRead( GetSrvProfString("Startpath","") + '\' + cArqErro ))
    else
        cMensagem := ""
    Endif
Return cMensagem

/*/{Protheus.doc} setEmpresa
 * Seta a empresa de acordo com o CNPJ
/*/
Static Function setEmpresa(cCNPJ)
    
    Local lRet := .F.
    
    OpenSM0(cEmpAnt)
    
    SM0->(DbGoTop())

    While SM0->(!Eof())
        If SM0->M0_CGC == cCNPJ
            cFilAnt := SM0->M0_CODFIL
            lRet    := .T.
            Exit
        EndIf
        SM0->(DbSkip())
    EndDo

Return lRet


/*/{Protheus.doc} getTomador
 * Retorna o CGC do tomador
/*/
Static Function getTomador(cTomador, oCTE)
    Local cRet      := ''
    Local aRet      := {}
    Local aTomador  := {}

    aAdd(aTomador, {'0', '_CTEPROC:_CTE:_INFCTE:_REM:_CNPJ:TEXT', '_CTEPROC:_CTE:_INFCTE:_REM', '_CTEPROC:_CTE:_INFCTE:_REM:_ENDERREME'    })
    aAdd(aTomador, {'1', '_CTEPROC:_CTE:_INFCTE:_EXPED:_CNPJ:TEXT', '_CTEPROC:_CTE:_INFCTE:_EXPED', '_CTEPROC:_CTE:_INFCTE:_EXPED:_ENDEREXPED'  })
    aAdd(aTomador, {'2', '_CTEPROC:_CTE:_INFCTE:_RECEB:_CNPJ:TEXT', '_CTEPROC:_CTE:_INFCTE:_RECEB', '_CTEPROC:_CTE:_INFCTE:_RECEB:_ENDERRECEB'  })
    aAdd(aTomador, {'3', '_CTEPROC:_CTE:_INFCTE:_DEST:_CNPJ:TEXT', '_CTEPROC:_CTE:_INFCTE:_DEST', '_CTEPROC:_CTE:_INFCTE:_DEST:_ENDERDEST'   })
    aAdd(aTomador, {'4', '_CTEPROC:_CTE:_INFCTE:_IDE:_TOMA4:_CNPJ:TEXT', '_CTEPROC:_CTE:_INFCTE:_IDE:_TOMA4', '_CTEPROC:_CTE:_INFCTE:_IDE:_TOMA4:_ENDERTOMA'})

    nPos    := aScan(aTomador,{|x| x[1] == cTomador})
    
    If nPos <> 0
        cRet := WSAdvValue(oCTE,aTomador[nPos][2],"string")
        If ValType(cRet) == 'U'
            aTomador := {}
            aAdd(aTomador, {'0', '_CTEPROC:_CTE:_INFCTE:_REM:_CPF:TEXT'    })
            aAdd(aTomador, {'1', '_CTEPROC:_CTE:_INFCTE:_EXPED:_CPF:TEXT'  })
            aAdd(aTomador, {'2', '_CTEPROC:_CTE:_INFCTE:_RECEB:_CPF:TEXT'  })
            aAdd(aTomador, {'3', '_CTEPROC:_CTE:_INFCTE:_DEST:_CPF:TEXT'   })
            aAdd(aTomador, {'4', '_CTEPROC:_CTE:_INFCTE:_IDE:_TOMA4:_CPF:TEXT'})

            cRet := WSAdvValue(oCTE,aTomador[nPos][2],"string")
            If ValType(cRet) == 'U'
                cRet   := ''
            EndIf
        EndIf
    EndIf

    if !empty(cRet)
        aRet := { cRet, aTomador[nPos][3], aTomador[nPos][4] }
    endif

Return aRet

/*/{Protheus.doc} getArray
 * Funcao que retorna um arary com os campos e dados que deverao ser gravados nas tabelas
/*/
Static Function getArray(oCTE, cTab, nRecNoSF2)
    Local aRet := {}
    Local i
    Local cAtivCPB   := SuperGetMv('MS_ATIVCPB',.F., '00000140')

    SF2->(DbGoTo(nRecNoSF2))
    nAliqCPB := SuperGetMv('MS_ALIQCPB', .F., 1.5)  

    If cTab == 'SF2'
        aAdd(aRet, {'F2_CHVNFE' , oCTE:_CTEPROC:_PROTCTE:_INFPROT:_CHCTE:TEXT})        
        aAdd(aRet, {'F2_HORA'   , SubStr(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_DHEMI:TEXT, 12,5) })
        aAdd(aRet, {'F2_UFORIG' , UPPER(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_UFINI:TEXT) })
        aAdd(aRet, {'F2_UFDEST' , UPPER(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_UFFIM:TEXT) })        
        aAdd(aRet, {'F2_EST'    , UPPER(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_UFFIM:TEXT) })    
        nAliqIcms := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_pICMS:TEXT","string")
        nValIcms  := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_vICMS:TEXT","string")
        If ValType( nAliqIcms) != 'U' .AND. ValType( nValIcms) != 'U'
            aAdd(aRet, {'F2_ALIQICM', Val(nAliqIcms) })        
            aAdd(aRet, {'F2_VALICM', Val(nValIcms) })        
        EndIf                      
    ElseIf cTab == 'SD2'
        aAdd(aRet, {'D2_CF'     , oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_CFOP:TEXT}) 
        aAdd(aRet, {'D2_EST'    , UPPER(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_UFFIM:TEXT) })                                  
        aAdd(aRet, {'D2_ALIQCPB', nAliqCPB})
        aAdd(aRet, {'D2_VALCPB' , Round(SF2->F2_VALMERC * (nAliqCPB / 100),2) })
        aAdd(aRet, {'D2_BASECPB', SF2->F2_VALMERC })
        aAdd(aRet, {'D2_CONTA', GetConta() })
        nAliqIcms := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_pICMS:TEXT","string")
        nValIcms  := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_vICMS:TEXT","string")
        If ValType( nAliqIcms) != 'U' .AND. ValType( nValIcms) != 'U'
            aAdd(aRet, {'D2_PICM', Val(nAliqIcms) })        
            aAdd(aRet, {'D2_VALICM', Val(nValIcms) })        
        EndIf  

    ElseIf cTab == 'SF3'
        aAdd(aRet, {'F3_CHVNFE' , oCTE:_CTEPROC:_PROTCTE:_INFPROT:_CHCTE:TEXT})
        aAdd(aRet, {'F3_CFO'    , oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_CFOP:TEXT})         
        aAdd(aRet, {'F3_ESPECIE', 'CTE'})         
        aAdd(aRet, {'F3_HORNFE' , SubStr(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_DHEMI:TEXT, 12,5) })
        aAdd(aRet, {'F3_ESTADO' , UPPER(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_UFFIM:TEXT) })      
        aAdd(aRet, {'F3_CLIDEST', cCODDes })
        aAdd(aRet, {'F3_LOJDEST', cLojDes })
        
        IF ValType(WSAdvValue(oCTE,"oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_VTOTTRIB:TEXT","string")) != "U"
            aAdd(aRet, {'F3_OBSICM', Val(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_VTOTTRIB:TEXT) })
        EndIf
        
        //CAMPOS CALCULADOS
        aAdd(aRet, {'F3_CSTPIS' , '01'})
        aAdd(aRet, {'F3_CSTCOF' , '01'})
        
        SF2->(DbGoTo(nRecNoSF2))
        nAliqCPB := SuperGetMv('MS_ALIQCPB', .F., 1.5)
        
        aAdd(aRet, {'F3_ALIQCPB', nAliqCPB })
        aAdd(aRet, {'F3_VALCPB' , Round(SF2->F2_VALMERC * (nAliqCPB / 100),2)})
        aAdd(aRet, {'F3_BASECPB', SF2->F2_VALMERC })
        
        aAdd(aRet, {'F3_CODRSEF', oCTE:_CTEPROC:_PROTCTE:_INFPROT:_CSTAT:TEXT })
        aAdd(aRet, {'F3_ATIVCPB' , cAtivCPB})
        aAdd(aRet, {'F3_CONTA' , GetConta()})
        

        nAliqIcms := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_pICMS:TEXT","string")
        nValIcms  := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_vICMS:TEXT","string")
        If ValType( nAliqIcms) != 'U' .AND. ValType( nValIcms) != 'U'
            aAdd(aRet, {'F3_ALIQICM', Val(nAliqIcms) })        
            aAdd(aRet, {'F3_VALICM', Val(nValIcms) })        
        EndIf  

        If AllTrim(ZZ1->ZZ1_ACAO) == 'E'
            aAdd(aRet, {'F3_DTCANC', StoD(StrTran(oCTE:_CTEPROC:_protCTe:_infProt:_dhRecbto:TEXT,"-","")) })    
        ElseIf AllTrim(ZZ1->ZZ1_ACAO) == 'U'   
            aAdd(aRet, {'F3_DTCANC', StoD(StrTran(oCTE:_CTEPROC:_protCTe:_infProt:_dhRecbto:TEXT,"-","")) })    
            aAdd(aRet, {'F3_CODRSEF', "102" })
            aAdd(aRet, {'F3_OBSERV', "NF INUTILIZADA" })
            aAdd(aRet, {'F3_CHVNFE ', "" })     
        EndIf

    ElseIf cTab == 'SFT'        
        aAdd(aRet, {'FT_CHVNFE' , oCTE:_CTEPROC:_PROTCTE:_INFPROT:_CHCTE:TEXT})
        aAdd(aRet, {'FT_CFOP'   , oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_CFOP:TEXT})         
        aAdd(aRet, {'FT_HORNFE' , SubStr(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_DHEMI:TEXT, 12,5) })
        aAdd(aRet, {'FT_ESTADO' , UPPER(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_UFFIM:TEXT) })      
        aAdd(aRet, {'FT_CLIDEST', cCODDes })
        aAdd(aRet, {'FT_LOJDEST', cLojDes })
        aAdd(aRet, {'FT_VALCONT', Val(oCTE:_CTEPROC:_CTE:_INFCTE:_VPREST:_VTPREST:TEXT) })
        aAdd(aRet, {'FT_TOTAL'  , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_VPREST:_VTPREST:TEXT) })
               
        // aAdd(aRet, {'FT_OBSERV' , oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_VTOTTRIB:TEXT })
        
        nValMerc  := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_VCARGA:TEXT","string")
        If ValType( nValMerc) != 'U'
            For i := 1 to Len(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ)
                If Alltrim(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_TPMED:TEXT) == 'PESO REAL'        
                    aAdd(aRet, {'FT_PESO'   , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_QCARGA:TEXT)})
                EndIf
                If Alltrim(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_TPMED:TEXT) == "QTDE DE VOLUMES"
                    aAdd(aRet, {'FT_QUANT'   , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_QCARGA:TEXT)})
                EndIf         
            Next
        EndIf

        aAdd(aRet, {'FT_ATIVCPB' , cAtivCPB})
        aAdd(aRet, {'FT_CSTPIS'  , '01'})
        
        nAliqPis    := GetMV('MV_TXPIS')        

        aAdd(aRet, {'FT_BASEPIS' , SF2->F2_BASIMP6})
        aAdd(aRet, {'FT_ALIQPIS' , nAliqPis})
        aAdd(aRet, {'FT_VALPIS'  , Round(SF2->F2_BASIMP6 * nAliqPis / 100,2)})
        
        nAliqCof    := GetMV('MV_TXCOFIN')
        
        aAdd(aRet, {'FT_CSTCOF'  , '01'})
        aAdd(aRet, {'FT_BASECOF' , SF2->F2_BASIMP5})
        aAdd(aRet, {'FT_ALIQCOF' , nAliqCof})
        aAdd(aRet, {'FT_VALCOF'  , Round(SF2->F2_BASIMP5 * nAliqCof / 100,2)})
        
        aAdd(aRet, {'FT_CONTA'  , GetConta()})

        aAdd(aRet, {'FT_ALIQCPB', nAliqCPB })
        aAdd(aRet, {'FT_VALCPB' , Round(SF2->F2_VALMERC * (nAliqCPB / 100),2)})
        aAdd(aRet, {'FT_BASECPB', SF2->F2_VALMERC })        

        aAdd(aRet, {'FT_CTIPI' , SuperGetMv('MS_CTIPI', .F., '53') })        
        aAdd(aRet, {'FT_GRPCST', SuperGetMv('MS_GRPCST', .F., '999') })     
        
        nAliqIcms := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_pICMS:TEXT","string")
        nValIcms  := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_vICMS:TEXT","string")
        If ValType( nAliqIcms) != 'U' .AND. ValType( nValIcms) != 'U'
            aAdd(aRet, {'FT_ALIQICM', Val(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_pICMS:TEXT) })        
            aAdd(aRet, {'FT_VALICM', Val(oCTE:_CTEPROC:_CTE:_INFCTE:_IMP:_ICMS:_ICMS00:_vICMS:TEXT) })        
        EndIf

        aAdd(aRet, {'FT_CLASFIS', StrZero(Val(SFT->FT_CLASFIS),3) })        
        
        If Alltrim(ZZ1->ZZ1_ACAO) == 'E'
            aAdd(aRet, {'FT_DTCANC', StoD(StrTran(oCTE:_CTEPROC:_PROTCTE:_infProt:_dhRecbto:TEXT,"-","")) })        
         ElseIf AllTrim(ZZ1->ZZ1_ACAO) == 'U'   
            aAdd(aRet, {'FT_DTCANC', StoD(StrTran(oCTE:_CTEPROC:_protCTe:_infProt:_dhRecbto:TEXT,"-","")) })    
            aAdd(aRet, {'FT_OBSERV', "NF INUTILIZADA" })
            aAdd(aRet, {'FT_CHVNFE ', "" })     
        EndIf

    ElseIf cTab == 'DT6'

        aAdd(aRet, {'DT6_FILIAL' , cFilAnt})        
        aAdd(aRet, {'DT6_FILDOC' , cFilAnt})        
        aAdd(aRet, {'DT6_FILORI' , cFilAnt})        
        aAdd(aRet, {'DT6_FILVGA' , cFilAnt})        
        aAdd(aRet, {'DT6_CHVCTE' , oCTE:_CTEPROC:_PROTCTE:_INFPROT:_CHCTE:TEXT})        
        aAdd(aRet, {'DT6_TIPO'   , 'CTE'})        
        aAdd(aRet, {'DT6_SERIE'  , cYNumSer })
        aAdd(aRet, {'DT6_DOC'    , cYNumNF})
        aAdd(aRet, {'DT6_VALIMP' , SF2->F2_VALICM })
        aAdd(aRet, {'DT6_DATEMI', StoD(StrTran(Left(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_DHEMI:TEXT,10),'-','')) })
        aAdd(aRet, {'DT6_HOREMI' , StrTran(SubStr(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_DHEMI:TEXT, 12,5),':','') })
        aAdd(aRet, {'DT6_TIPTRA' , oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_MODAL:TEXT })
        
        aAdd(aRet, {'DT6_CDRDES' , oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_CMUNFIM:TEXT })
        aAdd(aRet, {'DT6_CDRCAL' , oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_CMUNFIM:TEXT })
        
        cDescri := oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_xMunIni:TEXT 
        cCodMun := oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_CMUNINI:TEXT
        cPais  := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_REM:_enderReme:_CPAIS:TEXT","string")
        If ValType( cPais) == 'U' 
            cPais   := "105"
        EndIf
        cEst    := UPPER(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_UFIni:TEXT)
        
        cCDRORI := GrvGrpReg(cDescri, cCodMun, cPais, cEst)
        aAdd(aRet, {'DT6_CDRORI' , cCDRORI })
        cDescri := oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_xMunFIM:TEXT 
        cCodMun := oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_CMUNFIM:TEXT
        cPais  := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_dest:_enderDest:_CPAIS:TEXT","string")
        If ValType( cPais) == 'U' 
            cPais   := "105"
        EndIf
        cEst    := UPPER(oCTE:_CTEPROC:_CTE:_INFCTE:_IDE:_UFFIM:TEXT)
        
        cCDRDES := GrvGrpReg(cDescri, cCodMun, cPais, cEst)
        cCDRCAL := cCDRDES
        aAdd(aRet, {'DT6_CDRDES' , cCDRDES })
        aAdd(aRet, {'DT6_CDRCAL' , cCDRCAL })

        aAdd(aRet, {'DT6_CLICAL' , cCODCli })
        aAdd(aRet, {'DT6_LOJCAL' , cLojCli })
        aAdd(aRet, {'DT6_NOMCAL' , cNomCli })

        aAdd(aRet, {'DT6_CLIREM' , cCODRem })
        aAdd(aRet, {'DT6_LOJREM' , cLojRem })
        aAdd(aRet, {'DT6_NOMREM' , cNomRem })

        aAdd(aRet, {'DT6_CLIDES' , cCODDes })
        aAdd(aRet, {'DT6_LOJDES' , cLojDes })
        aAdd(aRet, {'DT6_NOMDES' , cNomDes })

        aAdd(aRet, {'DT6_CLIDEV' , cCODDes })
        aAdd(aRet, {'DT6_LOJDEV' , cLojDes })

        aAdd(aRet, {'DT6_VALTOT' , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_VPREST:_VTPREST:TEXT) })
        aAdd(aRet, {'DT6_VALFAT' , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_VPREST:_VTPREST:TEXT) })
        aAdd(aRet, {'DT6_VALFRE' , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_VPREST:_VTPREST:TEXT) })
        
        nAcresFret := 0
        
        //Calcula o valor do acrescimo ao frete
        If Valtype(oCTE:_CTEPROC:_CTE:_INFCTE:_VPREST:_COMP) == "A"
            For i := 1 to oCTE:_CTEPROC:_CTE:_INFCTE:_VPREST:_COMP
                If oCTE:_CTEPROC:_CTE:_INFCTE:_VPREST:_COMP[i]:_XNOME:TEXT != "FRETE PESO"
                    nAcresFret += Val(oCTE:_CTEPROC:_CTE:_INFCTE:_VPREST:_VTPREST:TEXT)
                EndIf            
            Next
        Else
            If oCTE:_CTEPROC:_CTE:_INFCTE:_VPREST:_COMP:_xNome:TEXT != "FRETE PESO"
                nAcresFret += Val(oCTE:_CTEPROC:_CTE:_INFCTE:_VPREST:_COMP:_VCOMP:TEXT)
            EndIf
        EndIF

        aAdd(aRet, {'DT6_ACRESC', nAcresFret })
        
        nValMerc  := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_VCARGA:TEXT","string")
        If ValType( nValMerc) != 'U'
            aAdd(aRet, {'DT6_VALMER' , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_VCARGA:TEXT) })
            //Percorre o arary para achar o peso e a quantidade
            For i := 1 to Len(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ)
                If Alltrim(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_TPMED:TEXT) == 'PESO REAL'        
                    aAdd(aRet, {'DT6_PESO'   , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_QCARGA:TEXT)})
                    aAdd(aRet, {'DT6_PESOM3' , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_QCARGA:TEXT)})
                EndIf
                If Alltrim(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_TPMED:TEXT) == "QTDE DE VOLUMES"
                    aAdd(aRet, {'DT6_QTDVOL'   , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_QCARGA:TEXT)})
                    aAdd(aRet, {'DT6_VOLORI'   , Val(oCTE:_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFCARGA:_INFQ[i]:_QCARGA:TEXT)})
                EndIf         
            Next
        EndIf
        aAdd(aRet, {'DT6_PROCTE'   , oCTE:_CTEPROC:_PROTCTE:_INFPROT:_NPROT:TEXT })
        aAdd(aRet, {'DT6_RETCTE'   , oCTE:_CTEPROC:_PROTCTE:_INFPROT:_NPROT:TEXT })

        cStatusCTE := oCTE:_CTEPROC:_PROTCTE:_INFPROT:_CSTAT:TEXT

        //autorizado,cancelado
        If cStatusCTE $ '100,101'    
            cSITCTE := '2'        
        //denegado
        ElseIf cStatusCTE $ '110'
            cSITCTE := '3'        
        //contingencia
        ElseIf cStatusCTE $ '108,109'
            cSITCTE := '4'
        EndIf

        aAdd(aRet, {'DT6_SITCTE' , cSITCTE })
        aAdd(aRet, {'DT6_CODOBS' , "" })
        aAdd(aRet, {'DT6_CODOBS' , "" })
        aAdd(aRet, {'DT6_TIPFRE' , IIF( cTpFrete == 'C', '1', '2') })
        cOBS := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_COMPL:_XOBS:TEXT","string")
       

    EndIf

Return aRet

/*/{Protheus.doc} GetNfs
/*/
Static Function getNfs(oCTE)
    Local aRet := {}
    Local xAux 
    Local i
    
    xAux := WSAdvValue(oCTE,"_CTEPROC:_CTE:_INFCTE:_INFCTENORM:_INFDOC:_INFNFE","array")
    
    If ValType(xAux) != 'U'
        If ValType(xAux) == 'A'
            For i := 1 to Len(xAux)
                aAdd(aRet, xAux[i]:_CHAVE:TEXT)
            Next
        ElseIf ValType(xAux) == 'O'
            aAdd(aRet, xAux:_CHAVE:TEXT)
        EndIf
    EndIf

Return aRet 

/*/{Protheus.doc} CancelaCTE
 * Exclui CTE
/*/
Static Function CancelaCTE()
    
    Local oPedido	:=	TNYXPEDIDOS():New() //Classe da Newib agisrn
    Local lRetorno := .F.
    Local cCNPJ := WSAdvValue(oCTE,"_procEventoCTe:_eventoCTe:_infEvento:_CNPJ:TEXT","string") 
    
    //cCnpj := SubStr(Alltrim(ZZ1->ZZ1_CHAVE), 7, 14)

    If ValType(cCNPJ) == "U"
        cMensagem := '_procEventoCTe:_eventoCTe:_infEvento:_CNPJ INVALIDA ' 
        return '_procEventoCTe:_eventoCTe:_infEvento:_CNPJ INVALIDA ' 
    EndIf

    If ! setEmpresa(cCNPJ)
        cMensagem := 'Cadastro de filial nao localizado com o CNPJ ' + cCNPJ
        return 'Cadastro de filial nao localizado com o CNPJ ' + cCNPJ
    EndIf
    
    //Valida antes de cancelar
    lRetorno := VldExist()
    BEGIN TRANSACTION
    If lRetorno
        cQryExl := " SELECT R_E_C_N_O_ AS RECNO FROM "  + RetSqlName('SF2') + " SF2"
        cQryExl += " WHERE SF2.D_E_L_E_T_ <> '*' AND F2_CHVNFE = '"+ZZ1->ZZ1_CHAVE+"' "
        
        If Select('QRYEXL') > 0
            QRYEXL->(dbclosearea())
        EndIf
        
        TcQuery cQryExl New Alias 'QRYEXL'
        
        If QRYEXL->(!Eof())
            nRecnoAux := QRYEXL->RECNO
            SF2->(DbGoTo(QRYEXL->RECNO))
                oPedido:DOC         := SF2->F2_DOC
                oPedido:SERIENF     := SF2->F2_SERIE
                oPedido:CLIENTENF   := SF2->F2_CLIENTE
                oPedido:LOJACLINF   := SF2->F2_LOJA
                oPedido:TIPONF      := SF2->F2_TIPO
                oPedido:lCRIASB2      := .F.
                If ! oPedido:EXCLUIRNF()
                    MostraErro(GetSrvProfString("Startpath","") , cArqErro )
                    cMensagem := Alltrim(MemoRead( GetSrvProfString("Startpath","") + '\' + cArqErro ))
                Else
                    oCTE := xmlParser(ZZ1->ZZ1_XML, "_", @cErro, @cAviso)    
                    //Cancela fiscal
                    SF2->(DbGoTo(nRecnoAux))    
                    cMensagem := CancFis()
                    If Empty(cMensagem)
                        cMensagem := ''
                    Else
                        DisarmTransaction()
                    EndIf
                    
                EndIf
        EndIF
    Else
        cMensagem := "Nota nao foi incluada no Protheus, portanto nao pode ser cancelada. Nao foi encontrado registro (ZZ1) de inclusao para esta nota."
    EndIf
    END TRANSACTION
Return cMensagem

/*/{Protheus.doc} VAlida e cria ZZ1 de inclusao
 * Antes realizar o cancelamento valida a existancia de um registro de
 * inclusao na tabela ZZ1.
/*/
Static Function VldExist()
    Local lRet      := .F.
    
    cQryZZ1u := " SELECT * FROM "  + RetSqlName('ZZ1') + " ZZ1"
    cQryZZ1u += " WHERE ZZ1.D_E_L_E_T_ <> '*' AND ZZ1_CHAVE = '"+ZZ1->ZZ1_CHAVE+"' "
    cQryZZ1u += " AND ZZ1_ACAO = 'I' AND ZZ1_STATUS = 'P' "
    
    If Select('QRYZZ1U') > 0
        QRYZZ1U->(dbclosearea())
    EndIf
    
    TcQuery cQryZZ1u New Alias 'QRYZZ1U'
    
    If QRYZZ1U->(!Eof())
        lRet := .T.
        QRYZZ1U->(dbSkip())
    EndIf

    
Return lRet

/*/{Protheus.doc} InutCTE
 * Inutilização de CTE
/*/
Static Function InutCTE() 
    
    Local aCabec := {}
    Local aItens := {}
    Local aLinha := {}
    Local cProduto := GetMv("MV_INUTPRO") //
    Local cCliInu  := GetMv("MV_INUTCLI") //
    Local cLojInu  := GetMv("MV_INUTLOJ") //
    Local cTesInu  := GetMv("MV_INUTTES") 
    
    PRIVATE lMsErroAuto := .F.

    cStat       := WSAdvValue(oCTE,"_soap_Envelope:_soap_Body:_cteInutilizacaoCTResult:_retInutCTe:_infInut:_cStat:TEXT"   ,"string")
    cCNPJ       := WSAdvValue(oCTE,"_soap_Envelope:_soap_Body:_cteInutilizacaoCTResult:_retInutCTe:_infInut:_CNPJ:TEXT"    ,"string")
    cSerie      := WSAdvValue(oCTE,"_soap_Envelope:_soap_Body:_cteInutilizacaoCTResult:_retInutCTe:_infInut:_SERIE:TEXT"   ,"string")
    cYNumNFIni  := WSAdvValue(oCTE,"_soap_Envelope:_soap_Body:_cteInutilizacaoCTResult:_retInutCTe:_infInut:_nCTIni:TEXT"  ,"string")
    cYNumNFFim  := WSAdvValue(oCTE,"_soap_Envelope:_soap_Body:_cteInutilizacaoCTResult:_retInutCTe:_infInut:_nCTFin:TEXT"  ,"string")
    dDataRec    := WSAdvValue(oCTE,"_soap_Envelope:_soap_Body:_cteInutilizacaoCTResult:_retInutCTe:_infInut:_dhRecbto:TEXT","string")
    If ValType(cCNPJ) == "U"
        cMensagem := "XML invalido entre em contato o TI NUCCI para resoluaao."+CRLF+" A 'tag_soap_Envelope:_soap_Body:_cteInutilizacaoCTResult:_retInutCTe:_infInut:_CNPJ' nao esta presente no XML. " 
        return cMensagem
    EndIf

    If ! setEmpresa(cCNPJ)
        cMensagem := "XML invalido  entre em contato o TI NUCCI para resoluaao."+CRLF+" A 'tag_soap_Envelope:_soap_Body:_cteInutilizacaoCTResult:_retInutCTe:_infInut:_CNPJ' nao esta presente no XML " 
        return 'Cadastro de filial nao localizado com o CNPJ ' + cCNPJ
    EndIf

    cYNumNFIni  := PadL(cYNumNFIni, len(SF2->F2_DOC), "0")
    cYNumNFFim  := PadL(cYNumNFFim, len(SF2->F2_DOC), "0")
    dDataRec    := StoD(StrTran(dDataRec,"-",""))
    dDataBase := dDataRec
    cMensagem := ""
    While cYNumNFIni <= cYNumNFFim
        
        aCabec := {}
        aItens := {}

        aadd(aCabec,{"F2_TIPO"     , "N"            })
        aadd(aCabec,{"F2_FORMUL"   , "N"            })
        aadd(aCabec,{"F2_DOC"      , cYNumNFIni     })
        aadd(aCabec,{"F2_SERIE"    , cSerie         })
        aadd(aCabec,{"F2_EMISSAO"  , dDataBase      })
        aadd(aCabec,{"F2_CLIENTE"  , PADR(cCliInu,LEN(SA1->A1_COD))        })
        aadd(aCabec,{"F2_LOJA"     , cLojInu        })
        aadd(aCabec,{"F2_ESPECIE"  , "CTE"          })
        aadd(aCabec,{"F2_COND"     , "001"          })
        aadd(aCabec,{"F2_DESCONT"  , 0              })
        aadd(aCabec,{"F2_FRETE"    , 0              })
        aadd(aCabec,{"F2_SEGURO"   , 0              })
        aadd(aCabec,{"F2_DESPESA"  , 0              })
    
        
        aLinha := {}
        aadd(aLinha,{"D2_COD"   , cProduto          , Nil})
        aadd(aLinha,{"D2_ITEM"  , StrZero(1,2)      , Nil})
        aadd(aLinha,{"D2_QUANT" , 1                 , Nil})
        aadd(aLinha,{"D2_PRCVEN", 0.01                 , Nil})
        aadd(aLinha,{"D2_TOTAL" , 0.01                 , Nil})
        aadd(aLinha,{"D2_TES"   , cTesInu           , Nil})
        aadd(aItens,aLinha)

        MSExecAuTo({|x,y| MATA920(x,y)},aCabec, aItens, 3)

        If !lMsErroAuto
            SF2->(DbSetOrder(1))
            If SF2->(DbSeek(xFilial("SF2") + PADR(cYNumNFIni,Len(SF2->F2_DOC)) + PADR(cSerie,Len(SF2->F2_SERIE)) + PADR(cCliInu,Len(SF2->F2_CLIENTE)) + PADR(cLojInu,Len(SF2->F2_LOJA))))
                ErrorBlock( {|e| cErrorBlock := e:Description + e:ErrorStack })
                BEGIN SEQUENCE
                    cXml := ZZ1->ZZ1_XML
                    cXml := StrTran(cXml,"env:","soap:")
                    oCTE := xmlParser(cXml, "_", @cErro, @cAviso)    
                    InutFis(/*.T.,SF2->(Recno())*/)
                    SD2->(DbSetOrder(3))
                    If SD2->(DbSeek(xFilial("SD2") + SF2->(F2_DOC + F2_SERIE + F2_CLIENTE + F2_LOJA + PADR(cProduto,LEN(SD2->D2_COD))) ))
                        RecLock('SD2', .F.)
                            SD2->(DbDelete())
                        SD2->(MsUnLock())
                    EndIf
                    RecLock('SF2', .F.)
                        SF2->(DbDelete())
                    SF2->(MsUnLock())
                        
                    cMensagem := "NF Gerada"

                    RECOVER
                END SEQUENCE 
                
            EndIf
        Else
            MostraErro(GetSrvProfString("Startpath","") , cArqErro )
            cMensagem := Alltrim(MemoRead( GetSrvProfString("Startpath","") + '\' + cArqErro ))
        EndIf
        cYNumNFIni := Soma1(cYNumNFIni)

    EndDo

Return 

/*/{Protheus.doc} GrvGrpReg
 * Grava grupo de regiao na tabela DUY, usado no madulo do TMS.
/*/
Static Function GrvGrpReg(cDescri, cCodMun, cPais, cEst)
    Local cQuery    := ""
    Local cCodDUY   := ""

    cQuery := " SELECT R_E_C_N_O_ AS RECNO FROM "  + RetSqlName('DUY') + " DUY"
    cQuery += " WHERE DUY.D_E_L_E_T_ <> '*' AND DUY_CODMUN = '"+Right(cCodMun,5)+"' AND DUY_EST = '"+cEst+"' "
    
    If Select('QRY') > 0
        QRY->(dbclosearea())
    EndIf
    
    TcQuery cQuery New Alias 'QRY'
    DUY->(DbSetOrder(1))
    If QRY->(Eof())
        RecLock('DUY', .T.)
            DUY->DUY_GRPVEN := GetSeqDUY()
            DUY->DUY_DESCRI := cDescri
            DUY->DUY_PAIS   := cPais
            DUY->DUY_CODMUN := Right(cCodMun,5)
            DUY->DUY_EST    := cEst   
        DUY->(MsUnLock())
        ConfirmSx8()
    Else
        DUY->(DbGoTo(QRY->RECNO))
    EndIf

    cCodDUY := DUY->DUY_GRPVEN

Return cCodDUY

/*/{Protheus.doc} GetSeqDUY
 * Busca uma nova sequencia
/*/
Static Function GetSeqDUY() 
    Local cRet := StrZero(0, len(DUY->DUY_GRPVEN))

    cQry := " SELECT MAX(DUY_GRPVEN) AS MAX FROM "  + RetSqlName('DUY') + " DUY"
    cQry += " WHERE DUY.D_E_L_E_T_ <> '*' "
    
    If Select('QRYDUY') > 0
        QRYDUY->(dbclosearea())
    EndIf
    
    TcQuery cQry New Alias 'QRYDUY'
    
    If QRYDUY->(!Eof())
        cRet :=  IIF(Empty(QRYDUY->MAX), cRet , Soma1(QRYDUY->MAX))
        QRYDUY->(dbSkip())
    EndIf

Return cRet

/*/{Protheus.doc} dadosvend
 * Recupera de um objeto xml os dados dos vendedores enviados na integracao
 * com o nucci
/*/
Static Function dadosVend(aXMLVend, nTotal)
    Local aRet := {}
    Local i 
    Local aAux := {'C','N','V'} //CPF, Nome e Valor
    
    //So trata se receber um array
    If ValType(aXMLVend) == 'A'
        
        //Cria uma matriz que ira guardar os vendedores - CPF, Nome, Valor, codinterno, percentual
        aRet := Array(3,5) 
        
        //Percorre o array pegando os dados
        For i := 1 to Len(aXMLVend)

            //Campo descritivo que representa o vendedor
            cCampo := WSAdvValue(aXMLVEND[i],"_XCAMPO:TEXT","string")            

            //Campo que representa o valor do campo para o vendedor
            cTexto := WSAdvValue(aXMLVEND[i],IIF(IsInCallStack('ProcessaNFSE'),"_P1_XTEXTO:TEXT" , "_XTEXTO:TEXT"),"string")            

            //Verifica se sao campos validos
            If ValType(cCampo) == 'C' .AND. ValType(cTexto) == 'C'

                //Verifica se e o campo customizado, podem haver outros tipos de campo
                If Left(cCampo,7) == 'TTTT_'

                    //Recupera o numero do vendedor
                    nVend       := Val(SubStr(cCampo, 8,1))

                    //Pega o tipo do campo
                    cTpCampo    := Right(cCampo,1)

                    //Veriica a posicao que ira colocar no array
                    nPosCampo   := aScan(aAux, cTpCampo)

                    //Se os dados forem validos, adiciona no retorno
                    If nVend > 0 .AND. nPosCampo > 0
                        aRet[nVend][nPosCampo] := cTexto                        
                    EndIf
                
                EndIf
            EndIf
        Next

    EndIf
    
    //Preenche o campo de codigo do vendedor
    For i := 1 to Len(aRet)
        If ValType(aRet[i][1]) != 'U' .AND. ValType(aRet[i][2]) != 'U' .AND. ValType(aRet[i][3]) != 'U'
            nValComis  := Val(aRet[i][3])
            //Calcula o valor do perecentual da comissao
            If ValType(nValComis) != 'U' .AND. nValComis > 0
                nPerComis  := Round(nValComis / nTotal * 100,2)
            Else
                nPerComis  := 0
            EndIf
            aRet[i][3] := nPerComis
            aRet[i][4] := retCodVend(aRet[i])
        EndIf
    Next

Return aRet

/*/{Protheus.doc} retCodVEnd
    (long_description)
 
/*/
Static Function retCodVEnd(aDados)
    Local cQuery 
    Local cRet
    
    cQuery := " SELECT A3_COD FROM " + RetSqlTab('SA3') 
    cQuery += " WHERE " + RetSqlDel('SA3')
    cQuery += " AND RTRIM(A3_CGC) = '" + Alltrim(aDados[1]) + "' "
    
    If Select('QRYSA3') > 0
        QRYSA3->(DbCloseArea())
    EndIf
        
    TcQuery cQuery New Alias 'QRYSA3'

    If QRYSA3->(!Eof())
        cRet := QRYSA3->A3_COD
    Else
        cRet := GETSXENUM('SA3', 'A3_COD')
        ConfirmSx8()
        RecLock('SA3', .T.)
            SA3->A3_FILIAL  := xFilial('SA3')
            SA3->A3_COD     := cRet
            SA3->A3_CGC     := aDados[1]
            SA3->A3_NOME    := aDados[2]
            SA3->A3_NREDUZ  := aDados[2]
        SA3->(MsUnLock())
    EndIf

Return cRet

Static Function GetConta()
    Local cRet      := Alltrim(SuperGetMv("MS_CTACTE", .f., ''))

Return cRet

Static Function CancFis()
    Local cDtcanc   := ""

    Local aAreaSF3 := SF3->(GetArea())
    Local aAreaSF2 := SF2->(GetArea())
    Local aAreaSFT := SFT->(GetArea())
    Local aAreaDT6 := DT6->(GetArea())
    Local aAreaSE1 := SE1->(GetArea())
    Local cRetorno     := ""

    SE1->(DbSetOrder(1))    
    SF3->(DbSetOrder(4))    
    SFT->(DbSetOrder(1))    
    DT6->(DbSetOrder(1))    

    cDtcanc := WSAdvValue(oCTE,"_PROCEVENTOCTE:_EVENTOCTE:_infEvento:_dhevento:TEXT","string") 
    If ValType(cDtcanc) == "U"
        cDtcanc := WSAdvValue(oCTE,"_retEventoCTe:_infEvento:_dhRegEvento:TEXT","string") 
        If ValType(cDtcanc) == "U"
             cDtcanc := WSAdvValue(oCTE,"_PROCEVENTOCTE:_retEventoCTe:_infEvento:_dhRegEvento:TEXT","string") 
        EndIf
    EndIf

    If ValType(cDtcanc) == "U"
        //cRetorno := "Data do evento nao encontrada no XML." + CRLF
        dDtCanc := dDataBase 
     Else
        dDtCanc := StoD(StrTran(cDtcanc,"-",""))
     EndIf
    
    If SFT->(DbSeek(SF2->F2_FILIAL + 'S' + SF2->(F2_SERIE + F2_DOC + F2_CLIENTE + F2_LOJA)))
        RecLock('SFT', .F.)
            SFT->FT_DTCANC := dDtCanc
        SFT->(MsUnLock())
    Else
        cRetorno := "SFT nao encontrada." + CRLF
    EndIf 

    If SF3->(DbSeek(SF2->(F2_FILIAL + F2_CLIENTE + F2_LOJA + F2_DOC + F2_SERIE)))
        RecLock('SF3', .F.)
            SF3->F3_DTCANC := dDtCanc
            SF3->F3_CODRSEF := "101" 
        SF3->(MsUnLock())
    Else
        cRetorno := "SF3 nao encontrada." + CRLF
    EndIf

     //Exclui DT6
    DT6->(DBOrderNickname("DT6CHVCTE"))
    If DT6->(DbSeek(xFilial("DT6") + SF2->F2_CHVNFE))
        RecLock('DT6', .F.)
            DT6->(DbDelete())
        DT6->(MsUnLock())
    EndIf
   
    SE1->(DbSetOrder(2))
    If SE1->(DbSeek(xFilial("SE1") + SF2->(F2_CLIENTE + F2_LOJA + F2_SERIE + F2_DOC ) ))
        lMsErroAuto := .F.
        aVetor := {}

        aAdd(aVetor, {"E1_FILIAL"   , SF2->F2_FILIAL                     } )
        aAdd(aVetor, {"E1_NUM"      , SF2->F2_DOC                        } )
        aAdd(aVetor, {"E1_PREFIXO"  , SF2->F2_SERIE                      } )
        aAdd(aVetor, {"E1_CLIENTE"  , SF2->F2_CLIENTE                    } )
        aAdd(aVetor, {"E1_LOJA"     , SF2->F2_LOJA                        } )
        aAdd(aVetor, {"E1_TIPO"     , PADR(SF2->F2_ESPECIE,LEN(SE1->E1_TIPO)) } )

        MSExecAuTo({|x,y|FINA040(x,y)},aVetor,5)
        If lMsErroAuto
            cRetorno := "Error ao cancelar tatulo (SE1)" + CRLF
            MostraErro(GetSrvProfString("Startpath","") , cArqErro )
            cRetorno += Alltrim(MemoRead( GetSrvProfString("Startpath","") + '\' + cArqErro ))
        EndIf
    Else
        cRetorno := "Error ao cancelar tatulo (SE1)" + CRLF
        cRetorno += "Tatulo nao encontrado na filial: " + xFilial('SE1')
    EndIf

    //Adicionado por Andre Vicente 24/10/2025
    If !lMsErroAuto
         RecLock('ZZ1', .F.)
            ZZ1->ZZ1_STATUS := 'P'
            ZZ1->ZZ1_STAFIS := 'A'
            ZZ1->(MsUnLock())
    Endif

    SF3->(RestArea(aAreaSF3))
    SFT->(RestArea(aAreaSFT))
    SF2->(RestArea(aAreaSF2))
    SE1->(RestArea(aAreaSE1))
    DT6->(RestArea(aAreaDT6))

Return cRetorno


Static Function InutFIS()

    Local aAreaSF3 := SF3->(GetArea())
    Local aAreaSF2 := SF2->(GetArea())
    Local aAreaSFT := SFT->(GetArea())
    Local aAreaSE1 := SE1->(GetArea())
    Local cRetorno     := ""
    
    SE1->(DbSetOrder(1))    
    SF3->(DbSetOrder(4))    
    SFT->(DbSetOrder(1))    
    
              
    If SFT->(DbSeek(SF2->F2_FILIAL + 'S' + SF2->(F2_SERIE + F2_DOC + F2_CLIENTE + F2_LOJA)))
        RecLock('SFT', .F.)
            SFT->FT_DTCANC := StoD(StrTran(oCTE:_soap_Envelope:_soap_Body:_cteInutilizacaoCTResult:_retInutCTe:_infInut:_dhRecbto:TEXT,"-",""))
            SFT->FT_OBSERV := "NF INUTILIZADA"
            SFT->FT_CHVNFE := "'"
        SFT->(MsUnLock())  
    Else
        cRetorno := "SFT nao encontrada." + CRLF
    EndIf 

    If SF3->(DbSeek(SF2->(F2_FILIAL + F2_CLIENTE + F2_LOJA + F2_DOC + F2_SERIE)))
        RecLock('SF3', .F.)
            SF3->F3_DTCANC := StoD(StrTran(oCTE:_soap_Envelope:_soap_Body:_cteInutilizacaoCTResult:_retInutCTe:_infInut:_dhRecbto:TEXT,"-",""))
            SF3->F3_CODRSEF := "102" 
            SF3->F3_OBSERV := "NF INUTILIZADA" 
            SF3->F3_CHVNFE := "" 
        SF3->(MsUnLock())
    Else
        cRetorno := "SF3 nao encontrada." + CRLF
    EndIf

    SE1->(DbSetOrder(2))
    If SE1->(DbSeek(xFilial("SE1") + SF2->(F2_CLIENTE + F2_LOJA + F2_SERIE + F2_DOC ) ))
        lMsErroAuto := .F.
        aVetor := {}

        aAdd(aVetor, {"E1_FILIAL"   , SF2->F2_FILIAL                     } )
        aAdd(aVetor, {"E1_NUM"      , SF2->F2_DOC                        } )
        aAdd(aVetor, {"E1_PREFIXO"  , SF2->F2_SERIE                      } )
        aAdd(aVetor, {"E1_CLIENTE"  , SF2->F2_CLIENTE                    } )
        aAdd(aVetor, {"E1_LOJA"     , SF2->F2_LOJA                        } )
        aAdd(aVetor, {"E1_TIPO"     , PADR(SF2->F2_ESPECIE,LEN(SE1->E1_TIPO)) } )

        MSExecAuTo({|x,y|FINA040(x,y)},aVetor,5)
        If lMsErroAuto
            cRetorno := "Error ao salvar SE1" + CRLF
            MostraErro(GetSrvProfString("Startpath","") , cArqErro )
            cRetorno += Alltrim(MemoRead( GetSrvProfString("Startpath","") + '\' + cArqErro ))
        EndIf
    EndIf


    SF3->(RestArea(aAreaSF3))
    SFT->(RestArea(aAreaSFT))
    SF2->(RestArea(aAreaSF2))
    SE1->(RestArea(aAreaSE1))

Return cRetorno

/*
User Function FUNC5CAN
    
    If Empty(FunName())
        PREPARE ENVIRONMENT EMPRESA '99' FILIAL '01'
    EndIf
    
    
    cQryAux :=  "SELECT ZZ1.R_E_C_N_O_ AS RECNO FROM "+RetSqlName("ZZ1")+ " ZZ1 "
    cQryAux += " WHERE  ZZ1_ACAO = 'I' AND ZZ1_CHAVE = '23200107189259000686570020000682791957718900' AND ZZ1.D_E_L_E_T_ <> '*'  "

    If Select('QRYAUX') > 0
        QRYAUX->(dbclosearea())
    EndIf    

    TcQuery cQryAux New Alias 'QRYAUX'

    While QRYAUX->(!Eof())
        U_LOSF0001(QRYAUX->RECNO)
        QRYAUX->(dbSkip())
    EndDo


Return

*/

/*/{Protheus.doc} getProdCte
    (long_description)
    @type  Static Function
    @author user
    @since 27/11/2025
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Static Function getProdCte(cChvOld)

    local aRetorno := {.F., "CTE Normal não localizado"}

    SF2->( DBOrderNickname( "IDXCHVNF" ) )
    if SF2->( dbSeek( xFilial("SF2") + cChvOld ) )
        SD2->( dbSetOrder( 3 ) )
        if SD2->( dbSeek( SF2->(F2_FILIAL + F2_DOC + F2_SERIE + F2_CLIENTE + F2_LOJA) ) )
            aRetorno := {.T., SD2->D2_COD}
        else 
            aRetorno := {.F., "Não foi localizado o código do produto do CTE Normal"}
        endif
    else 
        aRetorno := {.F., "Não foi localizado o CTE Normal deste XML de complemento."}
    endif

    
Return aRetorno

/*/{Protheus.doc} getClasPro
    (long_description)
    @type  Static Function
    @author user
    @since 26/12/2025
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Static Function getClasPro(cCodProd)

    default cCodProd := ""

    if Empty(cCodProd)
        return cCodProd
    endif

    BeginSql alias 'QRYX5'
        SELECT count(*) quantidade
          FROM %table:SX5% SX5
         WHERE SX5.X5_FILIAL = %xFilial:SX5%
           AND X5_TABELA = 'CP'
           AND X5_DESCRI = %exp:alltrim(cCodProd)%
           AND SX5.D_E_L_E_T_ <> '*'
    EndSql

    if QRYX5->quantidade > 0

        cCodigo := getSx8Num("SX5", "X5_CHAVE")

        recLock('SX5', .T.)
            SX5->X5_FILIAL := xFilial("SX5")
            SX5->X5_TABELA := 'CP'
            SX5->X5_CHAVE := cCodigo
            SX5->X5_DESCRI := cCodProd
            SX5->X5_DESCSPA := cCodProd
            SX5->X5_DESCENG := cCodProd
        SX5->(msUnlock())
        ConfirmSx8()
    endif 

    QRYX5->(dbclosearea())
    
Return cCodProd

/*/{Protheus.doc} gerError
    (long_description)
    @type  Static Function
    @author user
    @since 02/01/2026
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Static Function gerError(cMensagem)
    recLock( "ZZ1", .F. )
        ZZ1->ZZ1_STATUS := "E"
    ZZ1->( msUnlock() )

    CHKFILE("ZZ2")

    DBSelectArea( "ZZ2" )
    recLock("ZZ2", .T.)
        ZZ2->ZZ2_FILIAL := ZZ1->ZZ1_FILIAL 
        ZZ2->ZZ2_codigo := getSx8Num("ZZ2", "ZZ2_CODIGO")
        ZZ2->ZZ2_codzz1 := ZZ1->ZZ1_CODIGO
        ZZ2->ZZ2_status := "E"
        ZZ2->ZZ2_dtpros := dDataBase
        ZZ2->ZZ2_hrpros := time()
        ZZ2->ZZ2_log    := cMensagem
    ZZ2->( msUnLock() )
Return 

/*/{Protheus.doc} getCliente
    (long_description)
    @type  Static Function
    @author user
    @since 03/01/2026
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Static Function getCliente(cCNPJ, cIE, cUF)

    local aReturn := {}
    Local cWhere := "% %"

    default cCNPJ := ""
    default cIE   := ""
    default cUF   := ""

    if !Empty(cIE)
        cIE := Substr( alltrim( iif( alltrim( CUF ) == "PE", strzero( val( cIE ), 9 ), cIE ) ),1,TAMSX3("A1_INSCR")[1])
        cWhere := "% AND A1_INSCR = '" + alltrim(cIE) + "' %"
    endif

    if Empty(cCNPJ)
        return {.F., "CNPJ não pode ser vazio"}
    endif

    BeginSQL alias 'QRYCLI'
        SELECT * 
          FROM %TABLE:SA1% SA1
         WHERE A1_CGC = %exp:alltrim(cCNPJ)% AND 
          SA1.D_E_L_E_T_ = ' '
         %exp:cWhere%
         
    EndSql

    if QRYCLI->(!Eof())
        aReturn := {.T., QRYCLI->A1_COD, QRYCLI->A1_LOJA, alltrim(QRYCLI->A1_NOME)}
    else 
        aReturn := {.F., "Cliente não encontrado para o CNPJ: " + alltrim(cCNPJ) + iif(!Empty(cIE), " e IE: " + alltrim(cIE), "")}
    endif
    QRYCLI->(dbclosearea())
    
Return aReturn
